// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: payment/v1/payment.proto

package paymentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v11 "nweb.xyz/go/api-contracts-gen/common/v1"
	v1 "nweb.xyz/go/api-contracts-gen/subscription/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PaymentService_GetSubscriptionPlans_FullMethodName                  = "/payment.v1.PaymentService/GetSubscriptionPlans"
	PaymentService_GetWorkspaceSubscription_FullMethodName              = "/payment.v1.PaymentService/GetWorkspaceSubscription"
	PaymentService_UpdateWorkspaceSubscription_FullMethodName           = "/payment.v1.PaymentService/UpdateWorkspaceSubscription"
	PaymentService_StopWorkspaceSubscriptionCancellation_FullMethodName = "/payment.v1.PaymentService/StopWorkspaceSubscriptionCancellation"
	PaymentService_GetPortalSession_FullMethodName                      = "/payment.v1.PaymentService/GetPortalSession"
	PaymentService_GetSubscription_FullMethodName                       = "/payment.v1.PaymentService/GetSubscription"
	PaymentService_SetSubscription_FullMethodName                       = "/payment.v1.PaymentService/SetSubscription"
	PaymentService_DeleteSubscription_FullMethodName                    = "/payment.v1.PaymentService/DeleteSubscription"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	GetSubscriptionPlans(ctx context.Context, in *SubscriptionPlansRequest, opts ...grpc.CallOption) (*SubscriptionPlansResponse, error)
	GetWorkspaceSubscription(ctx context.Context, in *WorkspaceSubscriptionRequest, opts ...grpc.CallOption) (*v1.Subscription, error)
	UpdateWorkspaceSubscription(ctx context.Context, in *UpdateWorkspaceSubscriptionRequest, opts ...grpc.CallOption) (*UpdateWorkspaceSubscriptionResponse, error)
	StopWorkspaceSubscriptionCancellation(ctx context.Context, in *StopWorkspaceSubscriptionCancellationRequest, opts ...grpc.CallOption) (*v11.Empty, error)
	GetPortalSession(ctx context.Context, in *PortalSessionRequest, opts ...grpc.CallOption) (*PortalSessionResponse, error)
	// Following APIs should be used by BE calls only
	GetSubscription(ctx context.Context, in *v11.Id, opts ...grpc.CallOption) (*v1.Subscription, error)
	SetSubscription(ctx context.Context, in *v1.Subscription, opts ...grpc.CallOption) (*v11.Id, error)
	DeleteSubscription(ctx context.Context, in *v11.Id, opts ...grpc.CallOption) (*v11.Empty, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) GetSubscriptionPlans(ctx context.Context, in *SubscriptionPlansRequest, opts ...grpc.CallOption) (*SubscriptionPlansResponse, error) {
	out := new(SubscriptionPlansResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetSubscriptionPlans_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetWorkspaceSubscription(ctx context.Context, in *WorkspaceSubscriptionRequest, opts ...grpc.CallOption) (*v1.Subscription, error) {
	out := new(v1.Subscription)
	err := c.cc.Invoke(ctx, PaymentService_GetWorkspaceSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) UpdateWorkspaceSubscription(ctx context.Context, in *UpdateWorkspaceSubscriptionRequest, opts ...grpc.CallOption) (*UpdateWorkspaceSubscriptionResponse, error) {
	out := new(UpdateWorkspaceSubscriptionResponse)
	err := c.cc.Invoke(ctx, PaymentService_UpdateWorkspaceSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StopWorkspaceSubscriptionCancellation(ctx context.Context, in *StopWorkspaceSubscriptionCancellationRequest, opts ...grpc.CallOption) (*v11.Empty, error) {
	out := new(v11.Empty)
	err := c.cc.Invoke(ctx, PaymentService_StopWorkspaceSubscriptionCancellation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPortalSession(ctx context.Context, in *PortalSessionRequest, opts ...grpc.CallOption) (*PortalSessionResponse, error) {
	out := new(PortalSessionResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPortalSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetSubscription(ctx context.Context, in *v11.Id, opts ...grpc.CallOption) (*v1.Subscription, error) {
	out := new(v1.Subscription)
	err := c.cc.Invoke(ctx, PaymentService_GetSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) SetSubscription(ctx context.Context, in *v1.Subscription, opts ...grpc.CallOption) (*v11.Id, error) {
	out := new(v11.Id)
	err := c.cc.Invoke(ctx, PaymentService_SetSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) DeleteSubscription(ctx context.Context, in *v11.Id, opts ...grpc.CallOption) (*v11.Empty, error) {
	out := new(v11.Empty)
	err := c.cc.Invoke(ctx, PaymentService_DeleteSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility
type PaymentServiceServer interface {
	GetSubscriptionPlans(context.Context, *SubscriptionPlansRequest) (*SubscriptionPlansResponse, error)
	GetWorkspaceSubscription(context.Context, *WorkspaceSubscriptionRequest) (*v1.Subscription, error)
	UpdateWorkspaceSubscription(context.Context, *UpdateWorkspaceSubscriptionRequest) (*UpdateWorkspaceSubscriptionResponse, error)
	StopWorkspaceSubscriptionCancellation(context.Context, *StopWorkspaceSubscriptionCancellationRequest) (*v11.Empty, error)
	GetPortalSession(context.Context, *PortalSessionRequest) (*PortalSessionResponse, error)
	// Following APIs should be used by BE calls only
	GetSubscription(context.Context, *v11.Id) (*v1.Subscription, error)
	SetSubscription(context.Context, *v1.Subscription) (*v11.Id, error)
	DeleteSubscription(context.Context, *v11.Id) (*v11.Empty, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (UnimplementedPaymentServiceServer) GetSubscriptionPlans(context.Context, *SubscriptionPlansRequest) (*SubscriptionPlansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptionPlans not implemented")
}
func (UnimplementedPaymentServiceServer) GetWorkspaceSubscription(context.Context, *WorkspaceSubscriptionRequest) (*v1.Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspaceSubscription not implemented")
}
func (UnimplementedPaymentServiceServer) UpdateWorkspaceSubscription(context.Context, *UpdateWorkspaceSubscriptionRequest) (*UpdateWorkspaceSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkspaceSubscription not implemented")
}
func (UnimplementedPaymentServiceServer) StopWorkspaceSubscriptionCancellation(context.Context, *StopWorkspaceSubscriptionCancellationRequest) (*v11.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopWorkspaceSubscriptionCancellation not implemented")
}
func (UnimplementedPaymentServiceServer) GetPortalSession(context.Context, *PortalSessionRequest) (*PortalSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortalSession not implemented")
}
func (UnimplementedPaymentServiceServer) GetSubscription(context.Context, *v11.Id) (*v1.Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedPaymentServiceServer) SetSubscription(context.Context, *v1.Subscription) (*v11.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSubscription not implemented")
}
func (UnimplementedPaymentServiceServer) DeleteSubscription(context.Context, *v11.Id) (*v11.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_GetSubscriptionPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetSubscriptionPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetSubscriptionPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetSubscriptionPlans(ctx, req.(*SubscriptionPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetWorkspaceSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetWorkspaceSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetWorkspaceSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetWorkspaceSubscription(ctx, req.(*WorkspaceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_UpdateWorkspaceSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkspaceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).UpdateWorkspaceSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_UpdateWorkspaceSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).UpdateWorkspaceSubscription(ctx, req.(*UpdateWorkspaceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_StopWorkspaceSubscriptionCancellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWorkspaceSubscriptionCancellationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).StopWorkspaceSubscriptionCancellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_StopWorkspaceSubscriptionCancellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).StopWorkspaceSubscriptionCancellation(ctx, req.(*StopWorkspaceSubscriptionCancellationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPortalSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortalSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPortalSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPortalSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPortalSession(ctx, req.(*PortalSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetSubscription(ctx, req.(*v11.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_SetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).SetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_SetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).SetSubscription(ctx, req.(*v1.Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).DeleteSubscription(ctx, req.(*v11.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscriptionPlans",
			Handler:    _PaymentService_GetSubscriptionPlans_Handler,
		},
		{
			MethodName: "GetWorkspaceSubscription",
			Handler:    _PaymentService_GetWorkspaceSubscription_Handler,
		},
		{
			MethodName: "UpdateWorkspaceSubscription",
			Handler:    _PaymentService_UpdateWorkspaceSubscription_Handler,
		},
		{
			MethodName: "StopWorkspaceSubscriptionCancellation",
			Handler:    _PaymentService_StopWorkspaceSubscriptionCancellation_Handler,
		},
		{
			MethodName: "GetPortalSession",
			Handler:    _PaymentService_GetPortalSession_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _PaymentService_GetSubscription_Handler,
		},
		{
			MethodName: "SetSubscription",
			Handler:    _PaymentService_SetSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _PaymentService_DeleteSubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/payment.proto",
}
