// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: file/v1/service.proto

package filev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/file/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "file.v1.FileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FileServiceGetFilesProcedure is the fully-qualified name of the FileService's GetFiles RPC.
	FileServiceGetFilesProcedure = "/file.v1.FileService/GetFiles"
	// FileServiceGetFileProcedure is the fully-qualified name of the FileService's GetFile RPC.
	FileServiceGetFileProcedure = "/file.v1.FileService/GetFile"
	// FileServiceGetFileDetailsProcedure is the fully-qualified name of the FileService's
	// GetFileDetails RPC.
	FileServiceGetFileDetailsProcedure = "/file.v1.FileService/GetFileDetails"
	// FileServiceDeleteFileProcedure is the fully-qualified name of the FileService's DeleteFile RPC.
	FileServiceDeleteFileProcedure = "/file.v1.FileService/DeleteFile"
	// FileServiceGetFileSignedUrlProcedure is the fully-qualified name of the FileService's
	// GetFileSignedUrl RPC.
	FileServiceGetFileSignedUrlProcedure = "/file.v1.FileService/GetFileSignedUrl"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	fileServiceServiceDescriptor                = v1.File_file_v1_service_proto.Services().ByName("FileService")
	fileServiceGetFilesMethodDescriptor         = fileServiceServiceDescriptor.Methods().ByName("GetFiles")
	fileServiceGetFileMethodDescriptor          = fileServiceServiceDescriptor.Methods().ByName("GetFile")
	fileServiceGetFileDetailsMethodDescriptor   = fileServiceServiceDescriptor.Methods().ByName("GetFileDetails")
	fileServiceDeleteFileMethodDescriptor       = fileServiceServiceDescriptor.Methods().ByName("DeleteFile")
	fileServiceGetFileSignedUrlMethodDescriptor = fileServiceServiceDescriptor.Methods().ByName("GetFileSignedUrl")
)

// FileServiceClient is a client for the file.v1.FileService service.
type FileServiceClient interface {
	GetFiles(context.Context, *connect.Request[v1.FilesRequest]) (*connect.Response[v1.FilesResponse], error)
	GetFile(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.File], error)
	GetFileDetails(context.Context, *connect.Request[v1.FileDetailsRequest]) (*connect.Response[v1.File], error)
	DeleteFile(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	GetFileSignedUrl(context.Context, *connect.Request[v1.FileSignedUrlRequest]) (*connect.Response[v1.FileSignedUrlResponse], error)
}

// NewFileServiceClient constructs a client for the file.v1.FileService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &fileServiceClient{
		getFiles: connect.NewClient[v1.FilesRequest, v1.FilesResponse](
			httpClient,
			baseURL+FileServiceGetFilesProcedure,
			connect.WithSchema(fileServiceGetFilesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getFile: connect.NewClient[v11.Id, v1.File](
			httpClient,
			baseURL+FileServiceGetFileProcedure,
			connect.WithSchema(fileServiceGetFileMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getFileDetails: connect.NewClient[v1.FileDetailsRequest, v1.File](
			httpClient,
			baseURL+FileServiceGetFileDetailsProcedure,
			connect.WithSchema(fileServiceGetFileDetailsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteFile: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+FileServiceDeleteFileProcedure,
			connect.WithSchema(fileServiceDeleteFileMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getFileSignedUrl: connect.NewClient[v1.FileSignedUrlRequest, v1.FileSignedUrlResponse](
			httpClient,
			baseURL+FileServiceGetFileSignedUrlProcedure,
			connect.WithSchema(fileServiceGetFileSignedUrlMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// fileServiceClient implements FileServiceClient.
type fileServiceClient struct {
	getFiles         *connect.Client[v1.FilesRequest, v1.FilesResponse]
	getFile          *connect.Client[v11.Id, v1.File]
	getFileDetails   *connect.Client[v1.FileDetailsRequest, v1.File]
	deleteFile       *connect.Client[v11.Id, v11.Empty]
	getFileSignedUrl *connect.Client[v1.FileSignedUrlRequest, v1.FileSignedUrlResponse]
}

// GetFiles calls file.v1.FileService.GetFiles.
func (c *fileServiceClient) GetFiles(ctx context.Context, req *connect.Request[v1.FilesRequest]) (*connect.Response[v1.FilesResponse], error) {
	return c.getFiles.CallUnary(ctx, req)
}

// GetFile calls file.v1.FileService.GetFile.
func (c *fileServiceClient) GetFile(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.File], error) {
	return c.getFile.CallUnary(ctx, req)
}

// GetFileDetails calls file.v1.FileService.GetFileDetails.
func (c *fileServiceClient) GetFileDetails(ctx context.Context, req *connect.Request[v1.FileDetailsRequest]) (*connect.Response[v1.File], error) {
	return c.getFileDetails.CallUnary(ctx, req)
}

// DeleteFile calls file.v1.FileService.DeleteFile.
func (c *fileServiceClient) DeleteFile(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteFile.CallUnary(ctx, req)
}

// GetFileSignedUrl calls file.v1.FileService.GetFileSignedUrl.
func (c *fileServiceClient) GetFileSignedUrl(ctx context.Context, req *connect.Request[v1.FileSignedUrlRequest]) (*connect.Response[v1.FileSignedUrlResponse], error) {
	return c.getFileSignedUrl.CallUnary(ctx, req)
}

// FileServiceHandler is an implementation of the file.v1.FileService service.
type FileServiceHandler interface {
	GetFiles(context.Context, *connect.Request[v1.FilesRequest]) (*connect.Response[v1.FilesResponse], error)
	GetFile(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.File], error)
	GetFileDetails(context.Context, *connect.Request[v1.FileDetailsRequest]) (*connect.Response[v1.File], error)
	DeleteFile(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	GetFileSignedUrl(context.Context, *connect.Request[v1.FileSignedUrlRequest]) (*connect.Response[v1.FileSignedUrlResponse], error)
}

// NewFileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileServiceHandler(svc FileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fileServiceGetFilesHandler := connect.NewUnaryHandler(
		FileServiceGetFilesProcedure,
		svc.GetFiles,
		connect.WithSchema(fileServiceGetFilesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceGetFileHandler := connect.NewUnaryHandler(
		FileServiceGetFileProcedure,
		svc.GetFile,
		connect.WithSchema(fileServiceGetFileMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceGetFileDetailsHandler := connect.NewUnaryHandler(
		FileServiceGetFileDetailsProcedure,
		svc.GetFileDetails,
		connect.WithSchema(fileServiceGetFileDetailsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDeleteFileHandler := connect.NewUnaryHandler(
		FileServiceDeleteFileProcedure,
		svc.DeleteFile,
		connect.WithSchema(fileServiceDeleteFileMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceGetFileSignedUrlHandler := connect.NewUnaryHandler(
		FileServiceGetFileSignedUrlProcedure,
		svc.GetFileSignedUrl,
		connect.WithSchema(fileServiceGetFileSignedUrlMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/file.v1.FileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FileServiceGetFilesProcedure:
			fileServiceGetFilesHandler.ServeHTTP(w, r)
		case FileServiceGetFileProcedure:
			fileServiceGetFileHandler.ServeHTTP(w, r)
		case FileServiceGetFileDetailsProcedure:
			fileServiceGetFileDetailsHandler.ServeHTTP(w, r)
		case FileServiceDeleteFileProcedure:
			fileServiceDeleteFileHandler.ServeHTTP(w, r)
		case FileServiceGetFileSignedUrlProcedure:
			fileServiceGetFileSignedUrlHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileServiceHandler struct{}

func (UnimplementedFileServiceHandler) GetFiles(context.Context, *connect.Request[v1.FilesRequest]) (*connect.Response[v1.FilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.v1.FileService.GetFiles is not implemented"))
}

func (UnimplementedFileServiceHandler) GetFile(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.File], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.v1.FileService.GetFile is not implemented"))
}

func (UnimplementedFileServiceHandler) GetFileDetails(context.Context, *connect.Request[v1.FileDetailsRequest]) (*connect.Response[v1.File], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.v1.FileService.GetFileDetails is not implemented"))
}

func (UnimplementedFileServiceHandler) DeleteFile(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.v1.FileService.DeleteFile is not implemented"))
}

func (UnimplementedFileServiceHandler) GetFileSignedUrl(context.Context, *connect.Request[v1.FileSignedUrlRequest]) (*connect.Response[v1.FileSignedUrlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.v1.FileService.GetFileSignedUrl is not implemented"))
}
