// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: common/v1/soft_delete.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeletionInfo_Source int32

const (
	DeletionInfo_UNKNOWN DeletionInfo_Source = 0
	DeletionInfo_USER    DeletionInfo_Source = 1 // deleted directly via a DeleteX RPC
	DeletionInfo_CASCADE DeletionInfo_Source = 2 // deleted because a parent resource was deleted; see parent_nrn
)

// Enum value maps for DeletionInfo_Source.
var (
	DeletionInfo_Source_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER",
		2: "CASCADE",
	}
	DeletionInfo_Source_value = map[string]int32{
		"UNKNOWN": 0,
		"USER":    1,
		"CASCADE": 2,
	}
)

func (x DeletionInfo_Source) Enum() *DeletionInfo_Source {
	p := new(DeletionInfo_Source)
	*p = x
	return p
}

func (x DeletionInfo_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeletionInfo_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_soft_delete_proto_enumTypes[0].Descriptor()
}

func (DeletionInfo_Source) Type() protoreflect.EnumType {
	return &file_common_v1_soft_delete_proto_enumTypes[0]
}

func (x DeletionInfo_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeletionInfo_Source.Descriptor instead.
func (DeletionInfo_Source) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_soft_delete_proto_rawDescGZIP(), []int{0, 0}
}

// DeletionInfo captures why a soft-deleted document was deleted.
// Embedded in every entity that supports soft-delete alongside the is_deleted flag.
type DeletionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"source"
	Source DeletionInfo_Source `protobuf:"varint,1,opt,name=source,proto3,enum=common.v1.DeletionInfo_Source" json:"source,omitempty" bson:"source"`
	// NRN of the parent resource whose deletion cascaded here.
	// Set when source = CASCADE; empty for USER.
	// @inject_tag: bson:"parent_nrn"
	ParentNrn *Nrn `protobuf:"bytes,2,opt,name=parent_nrn,json=parentNrn,proto3" json:"parent_nrn,omitempty" bson:"parent_nrn"`
	// Optional free-text note for debugging/audit.
	// @inject_tag: bson:"note,omitempty"
	Note string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty" bson:"note,omitempty"`
}

func (x *DeletionInfo) Reset() {
	*x = DeletionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_soft_delete_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionInfo) ProtoMessage() {}

func (x *DeletionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_soft_delete_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionInfo.ProtoReflect.Descriptor instead.
func (*DeletionInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_soft_delete_proto_rawDescGZIP(), []int{0}
}

func (x *DeletionInfo) GetSource() DeletionInfo_Source {
	if x != nil {
		return x.Source
	}
	return DeletionInfo_UNKNOWN
}

func (x *DeletionInfo) GetParentNrn() *Nrn {
	if x != nil {
		return x.ParentNrn
	}
	return nil
}

func (x *DeletionInfo) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_common_v1_soft_delete_proto protoreflect.FileDescriptor

var file_common_v1_soft_delete_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x66, 0x74,
	0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x72, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x6e, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x72, 0x6e, 0x52, 0x09, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x4e, 0x72, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x41,
	0x53, 0x43, 0x41, 0x44, 0x45, 0x10, 0x02, 0x42, 0x97, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x53, 0x6f, 0x66, 0x74, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x6e, 0x77,
	0x65, 0x62, 0x2e, 0x78, 0x79, 0x7a, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x31,
	0xca, 0x02, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_soft_delete_proto_rawDescOnce sync.Once
	file_common_v1_soft_delete_proto_rawDescData = file_common_v1_soft_delete_proto_rawDesc
)

func file_common_v1_soft_delete_proto_rawDescGZIP() []byte {
	file_common_v1_soft_delete_proto_rawDescOnce.Do(func() {
		file_common_v1_soft_delete_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_soft_delete_proto_rawDescData)
	})
	return file_common_v1_soft_delete_proto_rawDescData
}

var file_common_v1_soft_delete_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_soft_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_soft_delete_proto_goTypes = []interface{}{
	(DeletionInfo_Source)(0), // 0: common.v1.DeletionInfo.Source
	(*DeletionInfo)(nil),     // 1: common.v1.DeletionInfo
	(*Nrn)(nil),              // 2: common.v1.Nrn
}
var file_common_v1_soft_delete_proto_depIdxs = []int32{
	0, // 0: common.v1.DeletionInfo.source:type_name -> common.v1.DeletionInfo.Source
	2, // 1: common.v1.DeletionInfo.parent_nrn:type_name -> common.v1.Nrn
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_soft_delete_proto_init() }
func file_common_v1_soft_delete_proto_init() {
	if File_common_v1_soft_delete_proto != nil {
		return
	}
	file_common_v1_nrn_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_common_v1_soft_delete_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_soft_delete_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_soft_delete_proto_goTypes,
		DependencyIndexes: file_common_v1_soft_delete_proto_depIdxs,
		EnumInfos:         file_common_v1_soft_delete_proto_enumTypes,
		MessageInfos:      file_common_v1_soft_delete_proto_msgTypes,
	}.Build()
	File_common_v1_soft_delete_proto = out.File
	file_common_v1_soft_delete_proto_rawDesc = nil
	file_common_v1_soft_delete_proto_goTypes = nil
	file_common_v1_soft_delete_proto_depIdxs = nil
}
