// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: common/v1/time.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeFilter_Operator int32

const (
	// GT: greater than
	TimeFilter_GT TimeFilter_Operator = 0
	// GTE: greater than or equal
	TimeFilter_GTE TimeFilter_Operator = 1
	// LT: less than
	TimeFilter_LT TimeFilter_Operator = 2
	// LTE: less than or equal
	TimeFilter_LTE TimeFilter_Operator = 3
)

// Enum value maps for TimeFilter_Operator.
var (
	TimeFilter_Operator_name = map[int32]string{
		0: "GT",
		1: "GTE",
		2: "LT",
		3: "LTE",
	}
	TimeFilter_Operator_value = map[string]int32{
		"GT":  0,
		"GTE": 1,
		"LT":  2,
		"LTE": 3,
	}
)

func (x TimeFilter_Operator) Enum() *TimeFilter_Operator {
	p := new(TimeFilter_Operator)
	*p = x
	return p
}

func (x TimeFilter_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeFilter_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_time_proto_enumTypes[0].Descriptor()
}

func (TimeFilter_Operator) Type() protoreflect.EnumType {
	return &file_common_v1_time_proto_enumTypes[0]
}

func (x TimeFilter_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeFilter_Operator.Descriptor instead.
func (TimeFilter_Operator) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_time_proto_rawDescGZIP(), []int{0, 0}
}

type TimeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator TimeFilter_Operator    `protobuf:"varint,1,opt,name=operator,proto3,enum=common.v1.TimeFilter_Operator" json:"operator,omitempty"`
	Value    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TimeFilter) Reset() {
	*x = TimeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_time_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeFilter) ProtoMessage() {}

func (x *TimeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_time_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeFilter.ProtoReflect.Descriptor instead.
func (*TimeFilter) Descriptor() ([]byte, []int) {
	return file_common_v1_time_proto_rawDescGZIP(), []int{0}
}

func (x *TimeFilter) GetOperator() TimeFilter_Operator {
	if x != nil {
		return x.Operator
	}
	return TimeFilter_GT
}

func (x *TimeFilter) GetValue() *timestamppb.Timestamp {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_common_v1_time_proto protoreflect.FileDescriptor

var file_common_v1_time_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x3a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x30, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x2c, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x47,
	0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02,
	0x4c, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x03, 0x42, 0x91, 0x01,
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x42,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x6e, 0x77,
	0x65, 0x62, 0x2e, 0x78, 0x79, 0x7a, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x31,
	0xca, 0x02, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_time_proto_rawDescOnce sync.Once
	file_common_v1_time_proto_rawDescData = file_common_v1_time_proto_rawDesc
)

func file_common_v1_time_proto_rawDescGZIP() []byte {
	file_common_v1_time_proto_rawDescOnce.Do(func() {
		file_common_v1_time_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_time_proto_rawDescData)
	})
	return file_common_v1_time_proto_rawDescData
}

var file_common_v1_time_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_time_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_time_proto_goTypes = []interface{}{
	(TimeFilter_Operator)(0),      // 0: common.v1.TimeFilter.Operator
	(*TimeFilter)(nil),            // 1: common.v1.TimeFilter
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_common_v1_time_proto_depIdxs = []int32{
	0, // 0: common.v1.TimeFilter.operator:type_name -> common.v1.TimeFilter.Operator
	2, // 1: common.v1.TimeFilter.value:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_time_proto_init() }
func file_common_v1_time_proto_init() {
	if File_common_v1_time_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_time_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_time_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_time_proto_goTypes,
		DependencyIndexes: file_common_v1_time_proto_depIdxs,
		EnumInfos:         file_common_v1_time_proto_enumTypes,
		MessageInfos:      file_common_v1_time_proto_msgTypes,
	}.Build()
	File_common_v1_time_proto = out.File
	file_common_v1_time_proto_rawDesc = nil
	file_common_v1_time_proto_goTypes = nil
	file_common_v1_time_proto_depIdxs = nil
}
