// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ai/chat/v1/chat.proto

package chatv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "nweb.xyz/go/api-contracts-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChatService_CreateThread_FullMethodName        = "/ai.chat.v1.ChatService/CreateThread"
	ChatService_UpdatePartialThread_FullMethodName = "/ai.chat.v1.ChatService/UpdatePartialThread"
	ChatService_GetThread_FullMethodName           = "/ai.chat.v1.ChatService/GetThread"
	ChatService_GetThreads_FullMethodName          = "/ai.chat.v1.ChatService/GetThreads"
	ChatService_DeleteThread_FullMethodName        = "/ai.chat.v1.ChatService/DeleteThread"
	ChatService_SendMessages_FullMethodName        = "/ai.chat.v1.ChatService/SendMessages"
	ChatService_GetMessage_FullMethodName          = "/ai.chat.v1.ChatService/GetMessage"
	ChatService_GetMessages_FullMethodName         = "/ai.chat.v1.ChatService/GetMessages"
	ChatService_DeleteMessage_FullMethodName       = "/ai.chat.v1.ChatService/DeleteMessage"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	CreateThread(ctx context.Context, in *Thread, opts ...grpc.CallOption) (*v1.Id, error)
	UpdatePartialThread(ctx context.Context, in *v1.PartialData, opts ...grpc.CallOption) (*v1.Id, error)
	GetThread(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Thread, error)
	GetThreads(ctx context.Context, in *ThreadsRequest, opts ...grpc.CallOption) (*ThreadsResponse, error)
	DeleteThread(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	// Send message and receive streaming responses with event or response messages
	//   - Client should send request with "request_id" (UUID) and use it as temporary identifier for request.
	//   - Server will response with "request_id" and correct "id" of the new message.
	//   - Server will return full Message for first time and ChunkedMessage for subsequent chunks of same message.
	SendMessages(ctx context.Context, in *SendMessagesRequest, opts ...grpc.CallOption) (ChatService_SendMessagesClient, error)
	GetMessage(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Message, error)
	GetMessages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	DeleteMessage(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CreateThread(ctx context.Context, in *Thread, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, ChatService_CreateThread_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdatePartialThread(ctx context.Context, in *v1.PartialData, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, ChatService_UpdatePartialThread_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetThread(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Thread, error) {
	out := new(Thread)
	err := c.cc.Invoke(ctx, ChatService_GetThread_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetThreads(ctx context.Context, in *ThreadsRequest, opts ...grpc.CallOption) (*ThreadsResponse, error) {
	out := new(ThreadsResponse)
	err := c.cc.Invoke(ctx, ChatService_GetThreads_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteThread(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ChatService_DeleteThread_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendMessages(ctx context.Context, in *SendMessagesRequest, opts ...grpc.CallOption) (ChatService_SendMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_SendMessages_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceSendMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_SendMessagesClient interface {
	Recv() (*SendMessagesResponse, error)
	grpc.ClientStream
}

type chatServiceSendMessagesClient struct {
	grpc.ClientStream
}

func (x *chatServiceSendMessagesClient) Recv() (*SendMessagesResponse, error) {
	m := new(SendMessagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) GetMessage(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, ChatService_GetMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetMessages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_GetMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteMessage(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ChatService_DeleteMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	CreateThread(context.Context, *Thread) (*v1.Id, error)
	UpdatePartialThread(context.Context, *v1.PartialData) (*v1.Id, error)
	GetThread(context.Context, *v1.Id) (*Thread, error)
	GetThreads(context.Context, *ThreadsRequest) (*ThreadsResponse, error)
	DeleteThread(context.Context, *v1.Id) (*v1.Empty, error)
	// Send message and receive streaming responses with event or response messages
	//   - Client should send request with "request_id" (UUID) and use it as temporary identifier for request.
	//   - Server will response with "request_id" and correct "id" of the new message.
	//   - Server will return full Message for first time and ChunkedMessage for subsequent chunks of same message.
	SendMessages(*SendMessagesRequest, ChatService_SendMessagesServer) error
	GetMessage(context.Context, *v1.Id) (*Message, error)
	GetMessages(context.Context, *MessagesRequest) (*MessagesResponse, error)
	DeleteMessage(context.Context, *v1.Id) (*v1.Empty, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) CreateThread(context.Context, *Thread) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateThread not implemented")
}
func (UnimplementedChatServiceServer) UpdatePartialThread(context.Context, *v1.PartialData) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePartialThread not implemented")
}
func (UnimplementedChatServiceServer) GetThread(context.Context, *v1.Id) (*Thread, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThread not implemented")
}
func (UnimplementedChatServiceServer) GetThreads(context.Context, *ThreadsRequest) (*ThreadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThreads not implemented")
}
func (UnimplementedChatServiceServer) DeleteThread(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteThread not implemented")
}
func (UnimplementedChatServiceServer) SendMessages(*SendMessagesRequest, ChatService_SendMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessages not implemented")
}
func (UnimplementedChatServiceServer) GetMessage(context.Context, *v1.Id) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedChatServiceServer) GetMessages(context.Context, *MessagesRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedChatServiceServer) DeleteMessage(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CreateThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Thread)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateThread(ctx, req.(*Thread))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdatePartialThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PartialData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdatePartialThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdatePartialThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdatePartialThread(ctx, req.(*v1.PartialData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetThread(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetThreads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetThreads(ctx, req.(*ThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteThread(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).SendMessages(m, &chatServiceSendMessagesServer{stream})
}

type ChatService_SendMessagesServer interface {
	Send(*SendMessagesResponse) error
	grpc.ServerStream
}

type chatServiceSendMessagesServer struct {
	grpc.ServerStream
}

func (x *chatServiceSendMessagesServer) Send(m *SendMessagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessage(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessages(ctx, req.(*MessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteMessage(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.chat.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateThread",
			Handler:    _ChatService_CreateThread_Handler,
		},
		{
			MethodName: "UpdatePartialThread",
			Handler:    _ChatService_UpdatePartialThread_Handler,
		},
		{
			MethodName: "GetThread",
			Handler:    _ChatService_GetThread_Handler,
		},
		{
			MethodName: "GetThreads",
			Handler:    _ChatService_GetThreads_Handler,
		},
		{
			MethodName: "DeleteThread",
			Handler:    _ChatService_DeleteThread_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _ChatService_GetMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _ChatService_GetMessages_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _ChatService_DeleteMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessages",
			Handler:       _ChatService_SendMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai/chat/v1/chat.proto",
}
