// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: project/v1/project.proto

package projectv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "nweb.xyz/retask-cli/proto-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProjectService_GetProjects_FullMethodName             = "/project.v1.ProjectService/GetProjects"
	ProjectService_GetProject_FullMethodName              = "/project.v1.ProjectService/GetProject"
	ProjectService_GetProjectByKey_FullMethodName         = "/project.v1.ProjectService/GetProjectByKey"
	ProjectService_SetProject_FullMethodName              = "/project.v1.ProjectService/SetProject"
	ProjectService_ArchiveProject_FullMethodName          = "/project.v1.ProjectService/ArchiveProject"
	ProjectService_UnarchiveProject_FullMethodName        = "/project.v1.ProjectService/UnarchiveProject"
	ProjectService_DeleteProject_FullMethodName           = "/project.v1.ProjectService/DeleteProject"
	ProjectService_GetProjectMembers_FullMethodName       = "/project.v1.ProjectService/GetProjectMembers"
	ProjectService_SetProjectMember_FullMethodName        = "/project.v1.ProjectService/SetProjectMember"
	ProjectService_RemoveProjectMember_FullMethodName     = "/project.v1.ProjectService/RemoveProjectMember"
	ProjectService_CheckProjectPermissions_FullMethodName = "/project.v1.ProjectService/CheckProjectPermissions"
	ProjectService_GetProjectsUsage_FullMethodName        = "/project.v1.ProjectService/GetProjectsUsage"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	GetProjects(ctx context.Context, in *ProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error)
	GetProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Project, error)
	GetProjectByKey(ctx context.Context, in *ProjectByKeyRequest, opts ...grpc.CallOption) (*Project, error)
	SetProject(ctx context.Context, in *Project, opts ...grpc.CallOption) (*v1.Id, error)
	ArchiveProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	UnarchiveProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	DeleteProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	GetProjectMembers(ctx context.Context, in *ProjectMembersRequest, opts ...grpc.CallOption) (*ProjectMembersResponse, error)
	SetProjectMember(ctx context.Context, in *ProjectMember, opts ...grpc.CallOption) (*v1.Empty, error)
	RemoveProjectMember(ctx context.Context, in *RemoveProjectMemberRequest, opts ...grpc.CallOption) (*v1.Empty, error)
	CheckProjectPermissions(ctx context.Context, in *CheckProjectPermissionsRequest, opts ...grpc.CallOption) (*CheckProjectPermissionsResponse, error)
	GetProjectsUsage(ctx context.Context, in *ProjectsUsageRequest, opts ...grpc.CallOption) (*ProjectsUsage, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) GetProjects(ctx context.Context, in *ProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error) {
	out := new(ProjectsResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetProjects_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_GetProject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectByKey(ctx context.Context, in *ProjectByKeyRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectByKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SetProject(ctx context.Context, in *Project, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, ProjectService_SetProject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ArchiveProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ProjectService_ArchiveProject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UnarchiveProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ProjectService_UnarchiveProject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProject(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ProjectService_DeleteProject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectMembers(ctx context.Context, in *ProjectMembersRequest, opts ...grpc.CallOption) (*ProjectMembersResponse, error) {
	out := new(ProjectMembersResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectMembers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SetProjectMember(ctx context.Context, in *ProjectMember, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ProjectService_SetProjectMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveProjectMember(ctx context.Context, in *RemoveProjectMemberRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ProjectService_RemoveProjectMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CheckProjectPermissions(ctx context.Context, in *CheckProjectPermissionsRequest, opts ...grpc.CallOption) (*CheckProjectPermissionsResponse, error) {
	out := new(CheckProjectPermissionsResponse)
	err := c.cc.Invoke(ctx, ProjectService_CheckProjectPermissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectsUsage(ctx context.Context, in *ProjectsUsageRequest, opts ...grpc.CallOption) (*ProjectsUsage, error) {
	out := new(ProjectsUsage)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectsUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility
type ProjectServiceServer interface {
	GetProjects(context.Context, *ProjectsRequest) (*ProjectsResponse, error)
	GetProject(context.Context, *v1.Id) (*Project, error)
	GetProjectByKey(context.Context, *ProjectByKeyRequest) (*Project, error)
	SetProject(context.Context, *Project) (*v1.Id, error)
	ArchiveProject(context.Context, *v1.Id) (*v1.Empty, error)
	UnarchiveProject(context.Context, *v1.Id) (*v1.Empty, error)
	DeleteProject(context.Context, *v1.Id) (*v1.Empty, error)
	GetProjectMembers(context.Context, *ProjectMembersRequest) (*ProjectMembersResponse, error)
	SetProjectMember(context.Context, *ProjectMember) (*v1.Empty, error)
	RemoveProjectMember(context.Context, *RemoveProjectMemberRequest) (*v1.Empty, error)
	CheckProjectPermissions(context.Context, *CheckProjectPermissionsRequest) (*CheckProjectPermissionsResponse, error)
	GetProjectsUsage(context.Context, *ProjectsUsageRequest) (*ProjectsUsage, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (UnimplementedProjectServiceServer) GetProjects(context.Context, *ProjectsRequest) (*ProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedProjectServiceServer) GetProject(context.Context, *v1.Id) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectByKey(context.Context, *ProjectByKeyRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectByKey not implemented")
}
func (UnimplementedProjectServiceServer) SetProject(context.Context, *Project) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProject not implemented")
}
func (UnimplementedProjectServiceServer) ArchiveProject(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveProject not implemented")
}
func (UnimplementedProjectServiceServer) UnarchiveProject(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnarchiveProject not implemented")
}
func (UnimplementedProjectServiceServer) DeleteProject(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectMembers(context.Context, *ProjectMembersRequest) (*ProjectMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectMembers not implemented")
}
func (UnimplementedProjectServiceServer) SetProjectMember(context.Context, *ProjectMember) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProjectMember not implemented")
}
func (UnimplementedProjectServiceServer) RemoveProjectMember(context.Context, *RemoveProjectMemberRequest) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProjectMember not implemented")
}
func (UnimplementedProjectServiceServer) CheckProjectPermissions(context.Context, *CheckProjectPermissionsRequest) (*CheckProjectPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckProjectPermissions not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectsUsage(context.Context, *ProjectsUsageRequest) (*ProjectsUsage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectsUsage not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjects(ctx, req.(*ProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProject(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectByKey(ctx, req.(*ProjectByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Project)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SetProject(ctx, req.(*Project))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ArchiveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ArchiveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ArchiveProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ArchiveProject(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UnarchiveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UnarchiveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UnarchiveProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UnarchiveProject(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProject(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectMembers(ctx, req.(*ProjectMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SetProjectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SetProjectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SetProjectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SetProjectMember(ctx, req.(*ProjectMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveProjectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveProjectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RemoveProjectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveProjectMember(ctx, req.(*RemoveProjectMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CheckProjectPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckProjectPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CheckProjectPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CheckProjectPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CheckProjectPermissions(ctx, req.(*CheckProjectPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectsUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectsUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectsUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectsUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectsUsage(ctx, req.(*ProjectsUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.v1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler:    _ProjectService_GetProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ProjectService_GetProject_Handler,
		},
		{
			MethodName: "GetProjectByKey",
			Handler:    _ProjectService_GetProjectByKey_Handler,
		},
		{
			MethodName: "SetProject",
			Handler:    _ProjectService_SetProject_Handler,
		},
		{
			MethodName: "ArchiveProject",
			Handler:    _ProjectService_ArchiveProject_Handler,
		},
		{
			MethodName: "UnarchiveProject",
			Handler:    _ProjectService_UnarchiveProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProjectService_DeleteProject_Handler,
		},
		{
			MethodName: "GetProjectMembers",
			Handler:    _ProjectService_GetProjectMembers_Handler,
		},
		{
			MethodName: "SetProjectMember",
			Handler:    _ProjectService_SetProjectMember_Handler,
		},
		{
			MethodName: "RemoveProjectMember",
			Handler:    _ProjectService_RemoveProjectMember_Handler,
		},
		{
			MethodName: "CheckProjectPermissions",
			Handler:    _ProjectService_CheckProjectPermissions_Handler,
		},
		{
			MethodName: "GetProjectsUsage",
			Handler:    _ProjectService_GetProjectsUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project/v1/project.proto",
}
