// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ai-gateway/v1/ai_gateway.proto

package ai_gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIGatewayService_Chat_FullMethodName = "/ai_gateway.v1.AIGatewayService/Chat"
)

// AIGatewayServiceClient is the client API for AIGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIGatewayServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (AIGatewayService_ChatClient, error)
}

type aIGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIGatewayServiceClient(cc grpc.ClientConnInterface) AIGatewayServiceClient {
	return &aIGatewayServiceClient{cc}
}

func (c *aIGatewayServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (AIGatewayService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &AIGatewayService_ServiceDesc.Streams[0], AIGatewayService_Chat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aIGatewayServiceChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AIGatewayService_ChatClient interface {
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type aIGatewayServiceChatClient struct {
	grpc.ClientStream
}

func (x *aIGatewayServiceChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AIGatewayServiceServer is the server API for AIGatewayService service.
// All implementations must embed UnimplementedAIGatewayServiceServer
// for forward compatibility
type AIGatewayServiceServer interface {
	Chat(*ChatRequest, AIGatewayService_ChatServer) error
	mustEmbedUnimplementedAIGatewayServiceServer()
}

// UnimplementedAIGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIGatewayServiceServer struct {
}

func (UnimplementedAIGatewayServiceServer) Chat(*ChatRequest, AIGatewayService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAIGatewayServiceServer) mustEmbedUnimplementedAIGatewayServiceServer() {}

// UnsafeAIGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIGatewayServiceServer will
// result in compilation errors.
type UnsafeAIGatewayServiceServer interface {
	mustEmbedUnimplementedAIGatewayServiceServer()
}

func RegisterAIGatewayServiceServer(s grpc.ServiceRegistrar, srv AIGatewayServiceServer) {
	s.RegisterService(&AIGatewayService_ServiceDesc, srv)
}

func _AIGatewayService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIGatewayServiceServer).Chat(m, &aIGatewayServiceChatServer{stream})
}

type AIGatewayService_ChatServer interface {
	Send(*ChatResponse) error
	grpc.ServerStream
}

type aIGatewayServiceChatServer struct {
	grpc.ServerStream
}

func (x *aIGatewayServiceChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

// AIGatewayService_ServiceDesc is the grpc.ServiceDesc for AIGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_gateway.v1.AIGatewayService",
	HandlerType: (*AIGatewayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIGatewayService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai-gateway/v1/ai_gateway.proto",
}
