// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: integration/v1/integration.proto

package integrationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/integration/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IntegrationServiceName is the fully-qualified name of the IntegrationService service.
	IntegrationServiceName = "integration.v1.IntegrationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IntegrationServiceGetProvidersProcedure is the fully-qualified name of the IntegrationService's
	// GetProviders RPC.
	IntegrationServiceGetProvidersProcedure = "/integration.v1.IntegrationService/GetProviders"
	// IntegrationServiceGetProviderProcedure is the fully-qualified name of the IntegrationService's
	// GetProvider RPC.
	IntegrationServiceGetProviderProcedure = "/integration.v1.IntegrationService/GetProvider"
	// IntegrationServiceGetIntegrationsProcedure is the fully-qualified name of the
	// IntegrationService's GetIntegrations RPC.
	IntegrationServiceGetIntegrationsProcedure = "/integration.v1.IntegrationService/GetIntegrations"
	// IntegrationServiceGetIntegrationProcedure is the fully-qualified name of the IntegrationService's
	// GetIntegration RPC.
	IntegrationServiceGetIntegrationProcedure = "/integration.v1.IntegrationService/GetIntegration"
	// IntegrationServiceSetIntegrationProcedure is the fully-qualified name of the IntegrationService's
	// SetIntegration RPC.
	IntegrationServiceSetIntegrationProcedure = "/integration.v1.IntegrationService/SetIntegration"
	// IntegrationServiceDeleteIntegrationProcedure is the fully-qualified name of the
	// IntegrationService's DeleteIntegration RPC.
	IntegrationServiceDeleteIntegrationProcedure = "/integration.v1.IntegrationService/DeleteIntegration"
	// IntegrationServiceAccessIntegrationProcedure is the fully-qualified name of the
	// IntegrationService's AccessIntegration RPC.
	IntegrationServiceAccessIntegrationProcedure = "/integration.v1.IntegrationService/AccessIntegration"
	// IntegrationServiceGetGithubReposProcedure is the fully-qualified name of the IntegrationService's
	// GetGithubRepos RPC.
	IntegrationServiceGetGithubReposProcedure = "/integration.v1.IntegrationService/GetGithubRepos"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	integrationServiceServiceDescriptor                 = v1.File_integration_v1_integration_proto.Services().ByName("IntegrationService")
	integrationServiceGetProvidersMethodDescriptor      = integrationServiceServiceDescriptor.Methods().ByName("GetProviders")
	integrationServiceGetProviderMethodDescriptor       = integrationServiceServiceDescriptor.Methods().ByName("GetProvider")
	integrationServiceGetIntegrationsMethodDescriptor   = integrationServiceServiceDescriptor.Methods().ByName("GetIntegrations")
	integrationServiceGetIntegrationMethodDescriptor    = integrationServiceServiceDescriptor.Methods().ByName("GetIntegration")
	integrationServiceSetIntegrationMethodDescriptor    = integrationServiceServiceDescriptor.Methods().ByName("SetIntegration")
	integrationServiceDeleteIntegrationMethodDescriptor = integrationServiceServiceDescriptor.Methods().ByName("DeleteIntegration")
	integrationServiceAccessIntegrationMethodDescriptor = integrationServiceServiceDescriptor.Methods().ByName("AccessIntegration")
	integrationServiceGetGithubReposMethodDescriptor    = integrationServiceServiceDescriptor.Methods().ByName("GetGithubRepos")
)

// IntegrationServiceClient is a client for the integration.v1.IntegrationService service.
type IntegrationServiceClient interface {
	GetProviders(context.Context, *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error)
	GetProvider(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Provider], error)
	GetIntegrations(context.Context, *connect.Request[v1.IntegrationsRequest]) (*connect.Response[v1.IntegrationsResponse], error)
	GetIntegration(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Integration], error)
	// Create or update. Uniqueness on (workspace_id, provider_id, level,
	// owner_member_id): a second call for the same tuple replaces the
	// existing row and rotates the underlying secrets.
	SetIntegration(context.Context, *connect.Request[v1.Integration]) (*connect.Response[v11.Id], error)
	// Hard delete. Removes the Integration row and emits IntegrationDeleted;
	// secret-manager listens and hard-deletes the underlying token secrets.
	DeleteIntegration(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// Resolves the right Integration for (workspace, provider, caller) and
	// returns plaintext credentials via secret-manager.
	// Resolution order: MEMBER (caller's user_nrn from gRPC metadata →
	// workspace_member_id) then WORKSPACE fallback.
	// Errors:
	//
	//	NOT_FOUND           — neither MEMBER nor WORKSPACE integration exists.
	//	FAILED_PRECONDITION — resolved integration's expires_at is past.
	AccessIntegration(context.Context, *connect.Request[v1.AccessIntegrationRequest]) (*connect.Response[v1.AccessIntegrationResponse], error)
	// Resolves the caller's GitHub integration and returns the repo catalog.
	// If level is set, uses that integration exactly; otherwise defaults to
	// MEMBER-first with WORKSPACE fallback. The raw token is never returned.
	GetGithubRepos(context.Context, *connect.Request[v1.GithubReposRequest]) (*connect.Response[v1.GithubReposResponse], error)
}

// NewIntegrationServiceClient constructs a client for the integration.v1.IntegrationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIntegrationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IntegrationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &integrationServiceClient{
		getProviders: connect.NewClient[v1.ProvidersRequest, v1.ProvidersResponse](
			httpClient,
			baseURL+IntegrationServiceGetProvidersProcedure,
			connect.WithSchema(integrationServiceGetProvidersMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getProvider: connect.NewClient[v11.Id, v1.Provider](
			httpClient,
			baseURL+IntegrationServiceGetProviderProcedure,
			connect.WithSchema(integrationServiceGetProviderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getIntegrations: connect.NewClient[v1.IntegrationsRequest, v1.IntegrationsResponse](
			httpClient,
			baseURL+IntegrationServiceGetIntegrationsProcedure,
			connect.WithSchema(integrationServiceGetIntegrationsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getIntegration: connect.NewClient[v11.Id, v1.Integration](
			httpClient,
			baseURL+IntegrationServiceGetIntegrationProcedure,
			connect.WithSchema(integrationServiceGetIntegrationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setIntegration: connect.NewClient[v1.Integration, v11.Id](
			httpClient,
			baseURL+IntegrationServiceSetIntegrationProcedure,
			connect.WithSchema(integrationServiceSetIntegrationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteIntegration: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+IntegrationServiceDeleteIntegrationProcedure,
			connect.WithSchema(integrationServiceDeleteIntegrationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		accessIntegration: connect.NewClient[v1.AccessIntegrationRequest, v1.AccessIntegrationResponse](
			httpClient,
			baseURL+IntegrationServiceAccessIntegrationProcedure,
			connect.WithSchema(integrationServiceAccessIntegrationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getGithubRepos: connect.NewClient[v1.GithubReposRequest, v1.GithubReposResponse](
			httpClient,
			baseURL+IntegrationServiceGetGithubReposProcedure,
			connect.WithSchema(integrationServiceGetGithubReposMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// integrationServiceClient implements IntegrationServiceClient.
type integrationServiceClient struct {
	getProviders      *connect.Client[v1.ProvidersRequest, v1.ProvidersResponse]
	getProvider       *connect.Client[v11.Id, v1.Provider]
	getIntegrations   *connect.Client[v1.IntegrationsRequest, v1.IntegrationsResponse]
	getIntegration    *connect.Client[v11.Id, v1.Integration]
	setIntegration    *connect.Client[v1.Integration, v11.Id]
	deleteIntegration *connect.Client[v11.Id, v11.Empty]
	accessIntegration *connect.Client[v1.AccessIntegrationRequest, v1.AccessIntegrationResponse]
	getGithubRepos    *connect.Client[v1.GithubReposRequest, v1.GithubReposResponse]
}

// GetProviders calls integration.v1.IntegrationService.GetProviders.
func (c *integrationServiceClient) GetProviders(ctx context.Context, req *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error) {
	return c.getProviders.CallUnary(ctx, req)
}

// GetProvider calls integration.v1.IntegrationService.GetProvider.
func (c *integrationServiceClient) GetProvider(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.Provider], error) {
	return c.getProvider.CallUnary(ctx, req)
}

// GetIntegrations calls integration.v1.IntegrationService.GetIntegrations.
func (c *integrationServiceClient) GetIntegrations(ctx context.Context, req *connect.Request[v1.IntegrationsRequest]) (*connect.Response[v1.IntegrationsResponse], error) {
	return c.getIntegrations.CallUnary(ctx, req)
}

// GetIntegration calls integration.v1.IntegrationService.GetIntegration.
func (c *integrationServiceClient) GetIntegration(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.Integration], error) {
	return c.getIntegration.CallUnary(ctx, req)
}

// SetIntegration calls integration.v1.IntegrationService.SetIntegration.
func (c *integrationServiceClient) SetIntegration(ctx context.Context, req *connect.Request[v1.Integration]) (*connect.Response[v11.Id], error) {
	return c.setIntegration.CallUnary(ctx, req)
}

// DeleteIntegration calls integration.v1.IntegrationService.DeleteIntegration.
func (c *integrationServiceClient) DeleteIntegration(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteIntegration.CallUnary(ctx, req)
}

// AccessIntegration calls integration.v1.IntegrationService.AccessIntegration.
func (c *integrationServiceClient) AccessIntegration(ctx context.Context, req *connect.Request[v1.AccessIntegrationRequest]) (*connect.Response[v1.AccessIntegrationResponse], error) {
	return c.accessIntegration.CallUnary(ctx, req)
}

// GetGithubRepos calls integration.v1.IntegrationService.GetGithubRepos.
func (c *integrationServiceClient) GetGithubRepos(ctx context.Context, req *connect.Request[v1.GithubReposRequest]) (*connect.Response[v1.GithubReposResponse], error) {
	return c.getGithubRepos.CallUnary(ctx, req)
}

// IntegrationServiceHandler is an implementation of the integration.v1.IntegrationService service.
type IntegrationServiceHandler interface {
	GetProviders(context.Context, *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error)
	GetProvider(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Provider], error)
	GetIntegrations(context.Context, *connect.Request[v1.IntegrationsRequest]) (*connect.Response[v1.IntegrationsResponse], error)
	GetIntegration(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Integration], error)
	// Create or update. Uniqueness on (workspace_id, provider_id, level,
	// owner_member_id): a second call for the same tuple replaces the
	// existing row and rotates the underlying secrets.
	SetIntegration(context.Context, *connect.Request[v1.Integration]) (*connect.Response[v11.Id], error)
	// Hard delete. Removes the Integration row and emits IntegrationDeleted;
	// secret-manager listens and hard-deletes the underlying token secrets.
	DeleteIntegration(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// Resolves the right Integration for (workspace, provider, caller) and
	// returns plaintext credentials via secret-manager.
	// Resolution order: MEMBER (caller's user_nrn from gRPC metadata →
	// workspace_member_id) then WORKSPACE fallback.
	// Errors:
	//
	//	NOT_FOUND           — neither MEMBER nor WORKSPACE integration exists.
	//	FAILED_PRECONDITION — resolved integration's expires_at is past.
	AccessIntegration(context.Context, *connect.Request[v1.AccessIntegrationRequest]) (*connect.Response[v1.AccessIntegrationResponse], error)
	// Resolves the caller's GitHub integration and returns the repo catalog.
	// If level is set, uses that integration exactly; otherwise defaults to
	// MEMBER-first with WORKSPACE fallback. The raw token is never returned.
	GetGithubRepos(context.Context, *connect.Request[v1.GithubReposRequest]) (*connect.Response[v1.GithubReposResponse], error)
}

// NewIntegrationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIntegrationServiceHandler(svc IntegrationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	integrationServiceGetProvidersHandler := connect.NewUnaryHandler(
		IntegrationServiceGetProvidersProcedure,
		svc.GetProviders,
		connect.WithSchema(integrationServiceGetProvidersMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	integrationServiceGetProviderHandler := connect.NewUnaryHandler(
		IntegrationServiceGetProviderProcedure,
		svc.GetProvider,
		connect.WithSchema(integrationServiceGetProviderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	integrationServiceGetIntegrationsHandler := connect.NewUnaryHandler(
		IntegrationServiceGetIntegrationsProcedure,
		svc.GetIntegrations,
		connect.WithSchema(integrationServiceGetIntegrationsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	integrationServiceGetIntegrationHandler := connect.NewUnaryHandler(
		IntegrationServiceGetIntegrationProcedure,
		svc.GetIntegration,
		connect.WithSchema(integrationServiceGetIntegrationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	integrationServiceSetIntegrationHandler := connect.NewUnaryHandler(
		IntegrationServiceSetIntegrationProcedure,
		svc.SetIntegration,
		connect.WithSchema(integrationServiceSetIntegrationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	integrationServiceDeleteIntegrationHandler := connect.NewUnaryHandler(
		IntegrationServiceDeleteIntegrationProcedure,
		svc.DeleteIntegration,
		connect.WithSchema(integrationServiceDeleteIntegrationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	integrationServiceAccessIntegrationHandler := connect.NewUnaryHandler(
		IntegrationServiceAccessIntegrationProcedure,
		svc.AccessIntegration,
		connect.WithSchema(integrationServiceAccessIntegrationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	integrationServiceGetGithubReposHandler := connect.NewUnaryHandler(
		IntegrationServiceGetGithubReposProcedure,
		svc.GetGithubRepos,
		connect.WithSchema(integrationServiceGetGithubReposMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/integration.v1.IntegrationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IntegrationServiceGetProvidersProcedure:
			integrationServiceGetProvidersHandler.ServeHTTP(w, r)
		case IntegrationServiceGetProviderProcedure:
			integrationServiceGetProviderHandler.ServeHTTP(w, r)
		case IntegrationServiceGetIntegrationsProcedure:
			integrationServiceGetIntegrationsHandler.ServeHTTP(w, r)
		case IntegrationServiceGetIntegrationProcedure:
			integrationServiceGetIntegrationHandler.ServeHTTP(w, r)
		case IntegrationServiceSetIntegrationProcedure:
			integrationServiceSetIntegrationHandler.ServeHTTP(w, r)
		case IntegrationServiceDeleteIntegrationProcedure:
			integrationServiceDeleteIntegrationHandler.ServeHTTP(w, r)
		case IntegrationServiceAccessIntegrationProcedure:
			integrationServiceAccessIntegrationHandler.ServeHTTP(w, r)
		case IntegrationServiceGetGithubReposProcedure:
			integrationServiceGetGithubReposHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIntegrationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIntegrationServiceHandler struct{}

func (UnimplementedIntegrationServiceHandler) GetProviders(context.Context, *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.GetProviders is not implemented"))
}

func (UnimplementedIntegrationServiceHandler) GetProvider(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Provider], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.GetProvider is not implemented"))
}

func (UnimplementedIntegrationServiceHandler) GetIntegrations(context.Context, *connect.Request[v1.IntegrationsRequest]) (*connect.Response[v1.IntegrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.GetIntegrations is not implemented"))
}

func (UnimplementedIntegrationServiceHandler) GetIntegration(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Integration], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.GetIntegration is not implemented"))
}

func (UnimplementedIntegrationServiceHandler) SetIntegration(context.Context, *connect.Request[v1.Integration]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.SetIntegration is not implemented"))
}

func (UnimplementedIntegrationServiceHandler) DeleteIntegration(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.DeleteIntegration is not implemented"))
}

func (UnimplementedIntegrationServiceHandler) AccessIntegration(context.Context, *connect.Request[v1.AccessIntegrationRequest]) (*connect.Response[v1.AccessIntegrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.AccessIntegration is not implemented"))
}

func (UnimplementedIntegrationServiceHandler) GetGithubRepos(context.Context, *connect.Request[v1.GithubReposRequest]) (*connect.Response[v1.GithubReposResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("integration.v1.IntegrationService.GetGithubRepos is not implemented"))
}
