// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ai/credit/v1/service.proto

package creditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "nweb.xyz/go/api-contracts-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CreditService_GetCreditBalance_FullMethodName       = "/ai.credit.v1.CreditService/GetCreditBalance"
	CreditService_GetCreditTransactions_FullMethodName  = "/ai.credit.v1.CreditService/GetCreditTransactions"
	CreditService_GetCreditWalletByOwner_FullMethodName = "/ai.credit.v1.CreditService/GetCreditWalletByOwner"
	CreditService_AuthorizeCredits_FullMethodName       = "/ai.credit.v1.CreditService/AuthorizeCredits"
	CreditService_RecordCredits_FullMethodName          = "/ai.credit.v1.CreditService/RecordCredits"
)

// CreditServiceClient is the client API for CreditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreditServiceClient interface {
	GetCreditBalance(ctx context.Context, in *CreditBalanceRequest, opts ...grpc.CallOption) (*CreditBalanceResponse, error)
	GetCreditTransactions(ctx context.Context, in *CreditTransactionsRequest, opts ...grpc.CallOption) (*CreditTransactionsResponse, error)
	// Following methods should be used by the internal BE services only
	GetCreditWalletByOwner(ctx context.Context, in *v1.Nrn, opts ...grpc.CallOption) (*CreditWallet, error)
	// AuthorizeCredits check balance and reject if balance is not enough
	// It is used to request the credit to approve the transaction
	AuthorizeCredits(ctx context.Context, in *CreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error)
	// RecordCredits record the transaction and update the balance
	// It is used to record the transaction already happened.
	RecordCredits(ctx context.Context, in *CreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error)
}

type creditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreditServiceClient(cc grpc.ClientConnInterface) CreditServiceClient {
	return &creditServiceClient{cc}
}

func (c *creditServiceClient) GetCreditBalance(ctx context.Context, in *CreditBalanceRequest, opts ...grpc.CallOption) (*CreditBalanceResponse, error) {
	out := new(CreditBalanceResponse)
	err := c.cc.Invoke(ctx, CreditService_GetCreditBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) GetCreditTransactions(ctx context.Context, in *CreditTransactionsRequest, opts ...grpc.CallOption) (*CreditTransactionsResponse, error) {
	out := new(CreditTransactionsResponse)
	err := c.cc.Invoke(ctx, CreditService_GetCreditTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) GetCreditWalletByOwner(ctx context.Context, in *v1.Nrn, opts ...grpc.CallOption) (*CreditWallet, error) {
	out := new(CreditWallet)
	err := c.cc.Invoke(ctx, CreditService_GetCreditWalletByOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) AuthorizeCredits(ctx context.Context, in *CreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error) {
	out := new(CreditsResponse)
	err := c.cc.Invoke(ctx, CreditService_AuthorizeCredits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) RecordCredits(ctx context.Context, in *CreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error) {
	out := new(CreditsResponse)
	err := c.cc.Invoke(ctx, CreditService_RecordCredits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditServiceServer is the server API for CreditService service.
// All implementations must embed UnimplementedCreditServiceServer
// for forward compatibility
type CreditServiceServer interface {
	GetCreditBalance(context.Context, *CreditBalanceRequest) (*CreditBalanceResponse, error)
	GetCreditTransactions(context.Context, *CreditTransactionsRequest) (*CreditTransactionsResponse, error)
	// Following methods should be used by the internal BE services only
	GetCreditWalletByOwner(context.Context, *v1.Nrn) (*CreditWallet, error)
	// AuthorizeCredits check balance and reject if balance is not enough
	// It is used to request the credit to approve the transaction
	AuthorizeCredits(context.Context, *CreditsRequest) (*CreditsResponse, error)
	// RecordCredits record the transaction and update the balance
	// It is used to record the transaction already happened.
	RecordCredits(context.Context, *CreditsRequest) (*CreditsResponse, error)
	mustEmbedUnimplementedCreditServiceServer()
}

// UnimplementedCreditServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCreditServiceServer struct {
}

func (UnimplementedCreditServiceServer) GetCreditBalance(context.Context, *CreditBalanceRequest) (*CreditBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreditBalance not implemented")
}
func (UnimplementedCreditServiceServer) GetCreditTransactions(context.Context, *CreditTransactionsRequest) (*CreditTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreditTransactions not implemented")
}
func (UnimplementedCreditServiceServer) GetCreditWalletByOwner(context.Context, *v1.Nrn) (*CreditWallet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreditWalletByOwner not implemented")
}
func (UnimplementedCreditServiceServer) AuthorizeCredits(context.Context, *CreditsRequest) (*CreditsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeCredits not implemented")
}
func (UnimplementedCreditServiceServer) RecordCredits(context.Context, *CreditsRequest) (*CreditsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordCredits not implemented")
}
func (UnimplementedCreditServiceServer) mustEmbedUnimplementedCreditServiceServer() {}

// UnsafeCreditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreditServiceServer will
// result in compilation errors.
type UnsafeCreditServiceServer interface {
	mustEmbedUnimplementedCreditServiceServer()
}

func RegisterCreditServiceServer(s grpc.ServiceRegistrar, srv CreditServiceServer) {
	s.RegisterService(&CreditService_ServiceDesc, srv)
}

func _CreditService_GetCreditBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetCreditBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetCreditBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetCreditBalance(ctx, req.(*CreditBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_GetCreditTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetCreditTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetCreditTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetCreditTransactions(ctx, req.(*CreditTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_GetCreditWalletByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Nrn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetCreditWalletByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetCreditWalletByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetCreditWalletByOwner(ctx, req.(*v1.Nrn))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_AuthorizeCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).AuthorizeCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_AuthorizeCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).AuthorizeCredits(ctx, req.(*CreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_RecordCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).RecordCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_RecordCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).RecordCredits(ctx, req.(*CreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreditService_ServiceDesc is the grpc.ServiceDesc for CreditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.credit.v1.CreditService",
	HandlerType: (*CreditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCreditBalance",
			Handler:    _CreditService_GetCreditBalance_Handler,
		},
		{
			MethodName: "GetCreditTransactions",
			Handler:    _CreditService_GetCreditTransactions_Handler,
		},
		{
			MethodName: "GetCreditWalletByOwner",
			Handler:    _CreditService_GetCreditWalletByOwner_Handler,
		},
		{
			MethodName: "AuthorizeCredits",
			Handler:    _CreditService_AuthorizeCredits_Handler,
		},
		{
			MethodName: "RecordCredits",
			Handler:    _CreditService_RecordCredits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai/credit/v1/service.proto",
}
