// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: retask/task/v1/task.proto

package taskv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/retask/task/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "retask.task.v1.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceGetTasksProcedure is the fully-qualified name of the TaskService's GetTasks RPC.
	TaskServiceGetTasksProcedure = "/retask.task.v1.TaskService/GetTasks"
	// TaskServiceGetTaskProcedure is the fully-qualified name of the TaskService's GetTask RPC.
	TaskServiceGetTaskProcedure = "/retask.task.v1.TaskService/GetTask"
	// TaskServiceGetTaskByKeyProcedure is the fully-qualified name of the TaskService's GetTaskByKey
	// RPC.
	TaskServiceGetTaskByKeyProcedure = "/retask.task.v1.TaskService/GetTaskByKey"
	// TaskServiceSetTaskProcedure is the fully-qualified name of the TaskService's SetTask RPC.
	TaskServiceSetTaskProcedure = "/retask.task.v1.TaskService/SetTask"
	// TaskServiceDeleteTaskProcedure is the fully-qualified name of the TaskService's DeleteTask RPC.
	TaskServiceDeleteTaskProcedure = "/retask.task.v1.TaskService/DeleteTask"
	// TaskServiceSetPartialTaskProcedure is the fully-qualified name of the TaskService's
	// SetPartialTask RPC.
	TaskServiceSetPartialTaskProcedure = "/retask.task.v1.TaskService/SetPartialTask"
	// TaskServiceAddTaskAttachmentProcedure is the fully-qualified name of the TaskService's
	// AddTaskAttachment RPC.
	TaskServiceAddTaskAttachmentProcedure = "/retask.task.v1.TaskService/AddTaskAttachment"
	// TaskServiceDeleteTaskAttachmentProcedure is the fully-qualified name of the TaskService's
	// DeleteTaskAttachment RPC.
	TaskServiceDeleteTaskAttachmentProcedure = "/retask.task.v1.TaskService/DeleteTaskAttachment"
	// TaskServiceGetTasksUsageProcedure is the fully-qualified name of the TaskService's GetTasksUsage
	// RPC.
	TaskServiceGetTasksUsageProcedure = "/retask.task.v1.TaskService/GetTasksUsage"
	// TaskServiceCheckTaskPermissionsProcedure is the fully-qualified name of the TaskService's
	// CheckTaskPermissions RPC.
	TaskServiceCheckTaskPermissionsProcedure = "/retask.task.v1.TaskService/CheckTaskPermissions"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	taskServiceServiceDescriptor                    = v1.File_retask_task_v1_task_proto.Services().ByName("TaskService")
	taskServiceGetTasksMethodDescriptor             = taskServiceServiceDescriptor.Methods().ByName("GetTasks")
	taskServiceGetTaskMethodDescriptor              = taskServiceServiceDescriptor.Methods().ByName("GetTask")
	taskServiceGetTaskByKeyMethodDescriptor         = taskServiceServiceDescriptor.Methods().ByName("GetTaskByKey")
	taskServiceSetTaskMethodDescriptor              = taskServiceServiceDescriptor.Methods().ByName("SetTask")
	taskServiceDeleteTaskMethodDescriptor           = taskServiceServiceDescriptor.Methods().ByName("DeleteTask")
	taskServiceSetPartialTaskMethodDescriptor       = taskServiceServiceDescriptor.Methods().ByName("SetPartialTask")
	taskServiceAddTaskAttachmentMethodDescriptor    = taskServiceServiceDescriptor.Methods().ByName("AddTaskAttachment")
	taskServiceDeleteTaskAttachmentMethodDescriptor = taskServiceServiceDescriptor.Methods().ByName("DeleteTaskAttachment")
	taskServiceGetTasksUsageMethodDescriptor        = taskServiceServiceDescriptor.Methods().ByName("GetTasksUsage")
	taskServiceCheckTaskPermissionsMethodDescriptor = taskServiceServiceDescriptor.Methods().ByName("CheckTaskPermissions")
)

// TaskServiceClient is a client for the retask.task.v1.TaskService service.
type TaskServiceClient interface {
	GetTasks(context.Context, *connect.Request[v1.TasksRequest]) (*connect.Response[v1.TasksResponse], error)
	GetTask(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Task], error)
	GetTaskByKey(context.Context, *connect.Request[v1.TaskByKeyRequest]) (*connect.Response[v1.Task], error)
	SetTask(context.Context, *connect.Request[v1.Task]) (*connect.Response[v11.Id], error)
	DeleteTask(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	SetPartialTask(context.Context, *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error)
	AddTaskAttachment(context.Context, *connect.Request[v1.AddTaskAttachmentRequest]) (*connect.Response[v1.Task], error)
	DeleteTaskAttachment(context.Context, *connect.Request[v1.DeleteTaskAttachmentRequest]) (*connect.Response[v1.Task], error)
	GetTasksUsage(context.Context, *connect.Request[v1.TasksUsageRequest]) (*connect.Response[v1.TasksUsage], error)
	CheckTaskPermissions(context.Context, *connect.Request[v1.CheckTaskPermissionsRequest]) (*connect.Response[v1.CheckTaskPermissionsResponse], error)
}

// NewTaskServiceClient constructs a client for the retask.task.v1.TaskService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &taskServiceClient{
		getTasks: connect.NewClient[v1.TasksRequest, v1.TasksResponse](
			httpClient,
			baseURL+TaskServiceGetTasksProcedure,
			connect.WithSchema(taskServiceGetTasksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v11.Id, v1.Task](
			httpClient,
			baseURL+TaskServiceGetTaskProcedure,
			connect.WithSchema(taskServiceGetTaskMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTaskByKey: connect.NewClient[v1.TaskByKeyRequest, v1.Task](
			httpClient,
			baseURL+TaskServiceGetTaskByKeyProcedure,
			connect.WithSchema(taskServiceGetTaskByKeyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setTask: connect.NewClient[v1.Task, v11.Id](
			httpClient,
			baseURL+TaskServiceSetTaskProcedure,
			connect.WithSchema(taskServiceSetTaskMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteTask: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+TaskServiceDeleteTaskProcedure,
			connect.WithSchema(taskServiceDeleteTaskMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setPartialTask: connect.NewClient[v11.PartialData, v11.Id](
			httpClient,
			baseURL+TaskServiceSetPartialTaskProcedure,
			connect.WithSchema(taskServiceSetPartialTaskMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		addTaskAttachment: connect.NewClient[v1.AddTaskAttachmentRequest, v1.Task](
			httpClient,
			baseURL+TaskServiceAddTaskAttachmentProcedure,
			connect.WithSchema(taskServiceAddTaskAttachmentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteTaskAttachment: connect.NewClient[v1.DeleteTaskAttachmentRequest, v1.Task](
			httpClient,
			baseURL+TaskServiceDeleteTaskAttachmentProcedure,
			connect.WithSchema(taskServiceDeleteTaskAttachmentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTasksUsage: connect.NewClient[v1.TasksUsageRequest, v1.TasksUsage](
			httpClient,
			baseURL+TaskServiceGetTasksUsageProcedure,
			connect.WithSchema(taskServiceGetTasksUsageMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		checkTaskPermissions: connect.NewClient[v1.CheckTaskPermissionsRequest, v1.CheckTaskPermissionsResponse](
			httpClient,
			baseURL+TaskServiceCheckTaskPermissionsProcedure,
			connect.WithSchema(taskServiceCheckTaskPermissionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	getTasks             *connect.Client[v1.TasksRequest, v1.TasksResponse]
	getTask              *connect.Client[v11.Id, v1.Task]
	getTaskByKey         *connect.Client[v1.TaskByKeyRequest, v1.Task]
	setTask              *connect.Client[v1.Task, v11.Id]
	deleteTask           *connect.Client[v11.Id, v11.Empty]
	setPartialTask       *connect.Client[v11.PartialData, v11.Id]
	addTaskAttachment    *connect.Client[v1.AddTaskAttachmentRequest, v1.Task]
	deleteTaskAttachment *connect.Client[v1.DeleteTaskAttachmentRequest, v1.Task]
	getTasksUsage        *connect.Client[v1.TasksUsageRequest, v1.TasksUsage]
	checkTaskPermissions *connect.Client[v1.CheckTaskPermissionsRequest, v1.CheckTaskPermissionsResponse]
}

// GetTasks calls retask.task.v1.TaskService.GetTasks.
func (c *taskServiceClient) GetTasks(ctx context.Context, req *connect.Request[v1.TasksRequest]) (*connect.Response[v1.TasksResponse], error) {
	return c.getTasks.CallUnary(ctx, req)
}

// GetTask calls retask.task.v1.TaskService.GetTask.
func (c *taskServiceClient) GetTask(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.Task], error) {
	return c.getTask.CallUnary(ctx, req)
}

// GetTaskByKey calls retask.task.v1.TaskService.GetTaskByKey.
func (c *taskServiceClient) GetTaskByKey(ctx context.Context, req *connect.Request[v1.TaskByKeyRequest]) (*connect.Response[v1.Task], error) {
	return c.getTaskByKey.CallUnary(ctx, req)
}

// SetTask calls retask.task.v1.TaskService.SetTask.
func (c *taskServiceClient) SetTask(ctx context.Context, req *connect.Request[v1.Task]) (*connect.Response[v11.Id], error) {
	return c.setTask.CallUnary(ctx, req)
}

// DeleteTask calls retask.task.v1.TaskService.DeleteTask.
func (c *taskServiceClient) DeleteTask(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteTask.CallUnary(ctx, req)
}

// SetPartialTask calls retask.task.v1.TaskService.SetPartialTask.
func (c *taskServiceClient) SetPartialTask(ctx context.Context, req *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error) {
	return c.setPartialTask.CallUnary(ctx, req)
}

// AddTaskAttachment calls retask.task.v1.TaskService.AddTaskAttachment.
func (c *taskServiceClient) AddTaskAttachment(ctx context.Context, req *connect.Request[v1.AddTaskAttachmentRequest]) (*connect.Response[v1.Task], error) {
	return c.addTaskAttachment.CallUnary(ctx, req)
}

// DeleteTaskAttachment calls retask.task.v1.TaskService.DeleteTaskAttachment.
func (c *taskServiceClient) DeleteTaskAttachment(ctx context.Context, req *connect.Request[v1.DeleteTaskAttachmentRequest]) (*connect.Response[v1.Task], error) {
	return c.deleteTaskAttachment.CallUnary(ctx, req)
}

// GetTasksUsage calls retask.task.v1.TaskService.GetTasksUsage.
func (c *taskServiceClient) GetTasksUsage(ctx context.Context, req *connect.Request[v1.TasksUsageRequest]) (*connect.Response[v1.TasksUsage], error) {
	return c.getTasksUsage.CallUnary(ctx, req)
}

// CheckTaskPermissions calls retask.task.v1.TaskService.CheckTaskPermissions.
func (c *taskServiceClient) CheckTaskPermissions(ctx context.Context, req *connect.Request[v1.CheckTaskPermissionsRequest]) (*connect.Response[v1.CheckTaskPermissionsResponse], error) {
	return c.checkTaskPermissions.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the retask.task.v1.TaskService service.
type TaskServiceHandler interface {
	GetTasks(context.Context, *connect.Request[v1.TasksRequest]) (*connect.Response[v1.TasksResponse], error)
	GetTask(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Task], error)
	GetTaskByKey(context.Context, *connect.Request[v1.TaskByKeyRequest]) (*connect.Response[v1.Task], error)
	SetTask(context.Context, *connect.Request[v1.Task]) (*connect.Response[v11.Id], error)
	DeleteTask(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	SetPartialTask(context.Context, *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error)
	AddTaskAttachment(context.Context, *connect.Request[v1.AddTaskAttachmentRequest]) (*connect.Response[v1.Task], error)
	DeleteTaskAttachment(context.Context, *connect.Request[v1.DeleteTaskAttachmentRequest]) (*connect.Response[v1.Task], error)
	GetTasksUsage(context.Context, *connect.Request[v1.TasksUsageRequest]) (*connect.Response[v1.TasksUsage], error)
	CheckTaskPermissions(context.Context, *connect.Request[v1.CheckTaskPermissionsRequest]) (*connect.Response[v1.CheckTaskPermissionsResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceGetTasksHandler := connect.NewUnaryHandler(
		TaskServiceGetTasksProcedure,
		svc.GetTasks,
		connect.WithSchema(taskServiceGetTasksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(taskServiceGetTaskMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskByKeyHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskByKeyProcedure,
		svc.GetTaskByKey,
		connect.WithSchema(taskServiceGetTaskByKeyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceSetTaskHandler := connect.NewUnaryHandler(
		TaskServiceSetTaskProcedure,
		svc.SetTask,
		connect.WithSchema(taskServiceSetTaskMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceDeleteTaskHandler := connect.NewUnaryHandler(
		TaskServiceDeleteTaskProcedure,
		svc.DeleteTask,
		connect.WithSchema(taskServiceDeleteTaskMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceSetPartialTaskHandler := connect.NewUnaryHandler(
		TaskServiceSetPartialTaskProcedure,
		svc.SetPartialTask,
		connect.WithSchema(taskServiceSetPartialTaskMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceAddTaskAttachmentHandler := connect.NewUnaryHandler(
		TaskServiceAddTaskAttachmentProcedure,
		svc.AddTaskAttachment,
		connect.WithSchema(taskServiceAddTaskAttachmentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceDeleteTaskAttachmentHandler := connect.NewUnaryHandler(
		TaskServiceDeleteTaskAttachmentProcedure,
		svc.DeleteTaskAttachment,
		connect.WithSchema(taskServiceDeleteTaskAttachmentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTasksUsageHandler := connect.NewUnaryHandler(
		TaskServiceGetTasksUsageProcedure,
		svc.GetTasksUsage,
		connect.WithSchema(taskServiceGetTasksUsageMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCheckTaskPermissionsHandler := connect.NewUnaryHandler(
		TaskServiceCheckTaskPermissionsProcedure,
		svc.CheckTaskPermissions,
		connect.WithSchema(taskServiceCheckTaskPermissionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/retask.task.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceGetTasksProcedure:
			taskServiceGetTasksHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskProcedure:
			taskServiceGetTaskHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskByKeyProcedure:
			taskServiceGetTaskByKeyHandler.ServeHTTP(w, r)
		case TaskServiceSetTaskProcedure:
			taskServiceSetTaskHandler.ServeHTTP(w, r)
		case TaskServiceDeleteTaskProcedure:
			taskServiceDeleteTaskHandler.ServeHTTP(w, r)
		case TaskServiceSetPartialTaskProcedure:
			taskServiceSetPartialTaskHandler.ServeHTTP(w, r)
		case TaskServiceAddTaskAttachmentProcedure:
			taskServiceAddTaskAttachmentHandler.ServeHTTP(w, r)
		case TaskServiceDeleteTaskAttachmentProcedure:
			taskServiceDeleteTaskAttachmentHandler.ServeHTTP(w, r)
		case TaskServiceGetTasksUsageProcedure:
			taskServiceGetTasksUsageHandler.ServeHTTP(w, r)
		case TaskServiceCheckTaskPermissionsProcedure:
			taskServiceCheckTaskPermissionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) GetTasks(context.Context, *connect.Request[v1.TasksRequest]) (*connect.Response[v1.TasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.GetTasks is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTask(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Task], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.GetTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTaskByKey(context.Context, *connect.Request[v1.TaskByKeyRequest]) (*connect.Response[v1.Task], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.GetTaskByKey is not implemented"))
}

func (UnimplementedTaskServiceHandler) SetTask(context.Context, *connect.Request[v1.Task]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.SetTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) DeleteTask(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.DeleteTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) SetPartialTask(context.Context, *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.SetPartialTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) AddTaskAttachment(context.Context, *connect.Request[v1.AddTaskAttachmentRequest]) (*connect.Response[v1.Task], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.AddTaskAttachment is not implemented"))
}

func (UnimplementedTaskServiceHandler) DeleteTaskAttachment(context.Context, *connect.Request[v1.DeleteTaskAttachmentRequest]) (*connect.Response[v1.Task], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.DeleteTaskAttachment is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTasksUsage(context.Context, *connect.Request[v1.TasksUsageRequest]) (*connect.Response[v1.TasksUsage], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.GetTasksUsage is not implemented"))
}

func (UnimplementedTaskServiceHandler) CheckTaskPermissions(context.Context, *connect.Request[v1.CheckTaskPermissionsRequest]) (*connect.Response[v1.CheckTaskPermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.task.v1.TaskService.CheckTaskPermissions is not implemented"))
}
