// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: customer/v1/customer.proto

package customerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CustomerService_GetMyProfile_FullMethodName            = "/customer.v1.CustomerService/GetMyProfile"
	CustomerService_SetMyProfile_FullMethodName            = "/customer.v1.CustomerService/SetMyProfile"
	CustomerService_GetOrCreateMyProfile_FullMethodName    = "/customer.v1.CustomerService/GetOrCreateMyProfile"
	CustomerService_GetCustomers_FullMethodName            = "/customer.v1.CustomerService/GetCustomers"
	CustomerService_GetCustomer_FullMethodName             = "/customer.v1.CustomerService/GetCustomer"
	CustomerService_GetCustomerByUserId_FullMethodName     = "/customer.v1.CustomerService/GetCustomerByUserId"
	CustomerService_SetCustomer_FullMethodName             = "/customer.v1.CustomerService/SetCustomer"
	CustomerService_DeleteCustomer_FullMethodName          = "/customer.v1.CustomerService/DeleteCustomer"
	CustomerService_GetCustomerRiskByUserId_FullMethodName = "/customer.v1.CustomerService/GetCustomerRiskByUserId"
)

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerServiceClient interface {
	GetMyProfile(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*Customer, error)
	SetMyProfile(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*v1.Id, error)
	GetOrCreateMyProfile(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error)
	// Following APIs should be used by BE calls only
	GetCustomers(ctx context.Context, in *CustomersRequest, opts ...grpc.CallOption) (*CustomersResponse, error)
	GetCustomer(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Customer, error)
	GetCustomerByUserId(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Customer, error)
	SetCustomer(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*v1.Id, error)
	DeleteCustomer(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	GetCustomerRiskByUserId(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*CustomerRisk, error)
}

type customerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerServiceClient(cc grpc.ClientConnInterface) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) GetMyProfile(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, CustomerService_GetMyProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) SetMyProfile(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, CustomerService_SetMyProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetOrCreateMyProfile(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, CustomerService_GetOrCreateMyProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomers(ctx context.Context, in *CustomersRequest, opts ...grpc.CallOption) (*CustomersResponse, error) {
	out := new(CustomersResponse)
	err := c.cc.Invoke(ctx, CustomerService_GetCustomers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomer(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, CustomerService_GetCustomer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomerByUserId(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, CustomerService_GetCustomerByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) SetCustomer(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, CustomerService_SetCustomer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) DeleteCustomer(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, CustomerService_DeleteCustomer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomerRiskByUserId(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*CustomerRisk, error) {
	out := new(CustomerRisk)
	err := c.cc.Invoke(ctx, CustomerService_GetCustomerRiskByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
// All implementations must embed UnimplementedCustomerServiceServer
// for forward compatibility
type CustomerServiceServer interface {
	GetMyProfile(context.Context, *v1.Empty) (*Customer, error)
	SetMyProfile(context.Context, *Customer) (*v1.Id, error)
	GetOrCreateMyProfile(context.Context, *Customer) (*Customer, error)
	// Following APIs should be used by BE calls only
	GetCustomers(context.Context, *CustomersRequest) (*CustomersResponse, error)
	GetCustomer(context.Context, *v1.Id) (*Customer, error)
	GetCustomerByUserId(context.Context, *v1.Id) (*Customer, error)
	SetCustomer(context.Context, *Customer) (*v1.Id, error)
	DeleteCustomer(context.Context, *v1.Id) (*v1.Empty, error)
	GetCustomerRiskByUserId(context.Context, *v1.Id) (*CustomerRisk, error)
	mustEmbedUnimplementedCustomerServiceServer()
}

// UnimplementedCustomerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (UnimplementedCustomerServiceServer) GetMyProfile(context.Context, *v1.Empty) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyProfile not implemented")
}
func (UnimplementedCustomerServiceServer) SetMyProfile(context.Context, *Customer) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMyProfile not implemented")
}
func (UnimplementedCustomerServiceServer) GetOrCreateMyProfile(context.Context, *Customer) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrCreateMyProfile not implemented")
}
func (UnimplementedCustomerServiceServer) GetCustomers(context.Context, *CustomersRequest) (*CustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomers not implemented")
}
func (UnimplementedCustomerServiceServer) GetCustomer(context.Context, *v1.Id) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (UnimplementedCustomerServiceServer) GetCustomerByUserId(context.Context, *v1.Id) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerByUserId not implemented")
}
func (UnimplementedCustomerServiceServer) SetCustomer(context.Context, *Customer) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCustomer not implemented")
}
func (UnimplementedCustomerServiceServer) DeleteCustomer(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomer not implemented")
}
func (UnimplementedCustomerServiceServer) GetCustomerRiskByUserId(context.Context, *v1.Id) (*CustomerRisk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerRiskByUserId not implemented")
}
func (UnimplementedCustomerServiceServer) mustEmbedUnimplementedCustomerServiceServer() {}

// UnsafeCustomerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServiceServer will
// result in compilation errors.
type UnsafeCustomerServiceServer interface {
	mustEmbedUnimplementedCustomerServiceServer()
}

func RegisterCustomerServiceServer(s grpc.ServiceRegistrar, srv CustomerServiceServer) {
	s.RegisterService(&CustomerService_ServiceDesc, srv)
}

func _CustomerService_GetMyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetMyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetMyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetMyProfile(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_SetMyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).SetMyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_SetMyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).SetMyProfile(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetOrCreateMyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetOrCreateMyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetOrCreateMyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetOrCreateMyProfile(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetCustomers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomers(ctx, req.(*CustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomer(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomerByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomerByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetCustomerByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomerByUserId(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_SetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).SetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_SetCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).SetCustomer(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_DeleteCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).DeleteCustomer(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomerRiskByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomerRiskByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_GetCustomerRiskByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomerRiskByUserId(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerService_ServiceDesc is the grpc.ServiceDesc for CustomerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.v1.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyProfile",
			Handler:    _CustomerService_GetMyProfile_Handler,
		},
		{
			MethodName: "SetMyProfile",
			Handler:    _CustomerService_SetMyProfile_Handler,
		},
		{
			MethodName: "GetOrCreateMyProfile",
			Handler:    _CustomerService_GetOrCreateMyProfile_Handler,
		},
		{
			MethodName: "GetCustomers",
			Handler:    _CustomerService_GetCustomers_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _CustomerService_GetCustomer_Handler,
		},
		{
			MethodName: "GetCustomerByUserId",
			Handler:    _CustomerService_GetCustomerByUserId_Handler,
		},
		{
			MethodName: "SetCustomer",
			Handler:    _CustomerService_SetCustomer_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _CustomerService_DeleteCustomer_Handler,
		},
		{
			MethodName: "GetCustomerRiskByUserId",
			Handler:    _CustomerService_GetCustomerRiskByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer/v1/customer.proto",
}
