// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cron/v1/cron.proto

package cronv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "nweb.xyz/go/api-contracts-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CronService_SetCron_FullMethodName     = "/cron.v1.CronService/SetCron"
	CronService_DeleteCrons_FullMethodName = "/cron.v1.CronService/DeleteCrons"
)

// CronServiceClient is the client API for CronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronServiceClient interface {
	// Cron's APIs
	SetCron(ctx context.Context, in *Cron, opts ...grpc.CallOption) (*v1.Id, error)
	DeleteCrons(ctx context.Context, in *v1.Ids, opts ...grpc.CallOption) (*v1.Summary, error)
}

type cronServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCronServiceClient(cc grpc.ClientConnInterface) CronServiceClient {
	return &cronServiceClient{cc}
}

func (c *cronServiceClient) SetCron(ctx context.Context, in *Cron, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, CronService_SetCron_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) DeleteCrons(ctx context.Context, in *v1.Ids, opts ...grpc.CallOption) (*v1.Summary, error) {
	out := new(v1.Summary)
	err := c.cc.Invoke(ctx, CronService_DeleteCrons_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServiceServer is the server API for CronService service.
// All implementations must embed UnimplementedCronServiceServer
// for forward compatibility
type CronServiceServer interface {
	// Cron's APIs
	SetCron(context.Context, *Cron) (*v1.Id, error)
	DeleteCrons(context.Context, *v1.Ids) (*v1.Summary, error)
	mustEmbedUnimplementedCronServiceServer()
}

// UnimplementedCronServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCronServiceServer struct {
}

func (UnimplementedCronServiceServer) SetCron(context.Context, *Cron) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCron not implemented")
}
func (UnimplementedCronServiceServer) DeleteCrons(context.Context, *v1.Ids) (*v1.Summary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCrons not implemented")
}
func (UnimplementedCronServiceServer) mustEmbedUnimplementedCronServiceServer() {}

// UnsafeCronServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronServiceServer will
// result in compilation errors.
type UnsafeCronServiceServer interface {
	mustEmbedUnimplementedCronServiceServer()
}

func RegisterCronServiceServer(s grpc.ServiceRegistrar, srv CronServiceServer) {
	s.RegisterService(&CronService_ServiceDesc, srv)
}

func _CronService_SetCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cron)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).SetCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_SetCron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).SetCron(ctx, req.(*Cron))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_DeleteCrons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Ids)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).DeleteCrons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_DeleteCrons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).DeleteCrons(ctx, req.(*v1.Ids))
	}
	return interceptor(ctx, in, info, handler)
}

// CronService_ServiceDesc is the grpc.ServiceDesc for CronService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cron.v1.CronService",
	HandlerType: (*CronServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetCron",
			Handler:    _CronService_SetCron_Handler,
		},
		{
			MethodName: "DeleteCrons",
			Handler:    _CronService_DeleteCrons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cron/v1/cron.proto",
}
