// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: retask/sandbox/v1/sandbox.proto

package sandboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/retask/sandbox/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SandboxServiceName is the fully-qualified name of the SandboxService service.
	SandboxServiceName = "retask.sandbox.v1.SandboxService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SandboxServiceGetSandboxesProcedure is the fully-qualified name of the SandboxService's
	// GetSandboxes RPC.
	SandboxServiceGetSandboxesProcedure = "/retask.sandbox.v1.SandboxService/GetSandboxes"
	// SandboxServiceGetSandboxProcedure is the fully-qualified name of the SandboxService's GetSandbox
	// RPC.
	SandboxServiceGetSandboxProcedure = "/retask.sandbox.v1.SandboxService/GetSandbox"
	// SandboxServiceGetSandboxRuntimeProcedure is the fully-qualified name of the SandboxService's
	// GetSandboxRuntime RPC.
	SandboxServiceGetSandboxRuntimeProcedure = "/retask.sandbox.v1.SandboxService/GetSandboxRuntime"
	// SandboxServiceSetSandboxProcedure is the fully-qualified name of the SandboxService's SetSandbox
	// RPC.
	SandboxServiceSetSandboxProcedure = "/retask.sandbox.v1.SandboxService/SetSandbox"
	// SandboxServiceStopSandboxProcedure is the fully-qualified name of the SandboxService's
	// StopSandbox RPC.
	SandboxServiceStopSandboxProcedure = "/retask.sandbox.v1.SandboxService/StopSandbox"
	// SandboxServiceDeleteSandboxProcedure is the fully-qualified name of the SandboxService's
	// DeleteSandbox RPC.
	SandboxServiceDeleteSandboxProcedure = "/retask.sandbox.v1.SandboxService/DeleteSandbox"
	// SandboxServiceGetSessionsProcedure is the fully-qualified name of the SandboxService's
	// GetSessions RPC.
	SandboxServiceGetSessionsProcedure = "/retask.sandbox.v1.SandboxService/GetSessions"
	// SandboxServiceGetSessionProcedure is the fully-qualified name of the SandboxService's GetSession
	// RPC.
	SandboxServiceGetSessionProcedure = "/retask.sandbox.v1.SandboxService/GetSession"
	// SandboxServiceNewSessionProcedure is the fully-qualified name of the SandboxService's NewSession
	// RPC.
	SandboxServiceNewSessionProcedure = "/retask.sandbox.v1.SandboxService/NewSession"
	// SandboxServiceSetPartialSessionProcedure is the fully-qualified name of the SandboxService's
	// SetPartialSession RPC.
	SandboxServiceSetPartialSessionProcedure = "/retask.sandbox.v1.SandboxService/SetPartialSession"
	// SandboxServiceConnectSessionProcedure is the fully-qualified name of the SandboxService's
	// ConnectSession RPC.
	SandboxServiceConnectSessionProcedure = "/retask.sandbox.v1.SandboxService/ConnectSession"
	// SandboxServiceGetSessionRuntimeProcedure is the fully-qualified name of the SandboxService's
	// GetSessionRuntime RPC.
	SandboxServiceGetSessionRuntimeProcedure = "/retask.sandbox.v1.SandboxService/GetSessionRuntime"
	// SandboxServiceStopSessionProcedure is the fully-qualified name of the SandboxService's
	// StopSession RPC.
	SandboxServiceStopSessionProcedure = "/retask.sandbox.v1.SandboxService/StopSession"
	// SandboxServiceDeleteSessionProcedure is the fully-qualified name of the SandboxService's
	// DeleteSession RPC.
	SandboxServiceDeleteSessionProcedure = "/retask.sandbox.v1.SandboxService/DeleteSession"
	// SandboxServiceReportSessionStatusProcedure is the fully-qualified name of the SandboxService's
	// ReportSessionStatus RPC.
	SandboxServiceReportSessionStatusProcedure = "/retask.sandbox.v1.SandboxService/ReportSessionStatus"
	// SandboxServiceReportSandboxStatusProcedure is the fully-qualified name of the SandboxService's
	// ReportSandboxStatus RPC.
	SandboxServiceReportSandboxStatusProcedure = "/retask.sandbox.v1.SandboxService/ReportSandboxStatus"
	// SandboxServiceGetSandboxTemplatesProcedure is the fully-qualified name of the SandboxService's
	// GetSandboxTemplates RPC.
	SandboxServiceGetSandboxTemplatesProcedure = "/retask.sandbox.v1.SandboxService/GetSandboxTemplates"
	// SandboxServiceGetSandboxTemplateProcedure is the fully-qualified name of the SandboxService's
	// GetSandboxTemplate RPC.
	SandboxServiceGetSandboxTemplateProcedure = "/retask.sandbox.v1.SandboxService/GetSandboxTemplate"
	// SandboxServiceSetSandboxTemplateProcedure is the fully-qualified name of the SandboxService's
	// SetSandboxTemplate RPC.
	SandboxServiceSetSandboxTemplateProcedure = "/retask.sandbox.v1.SandboxService/SetSandboxTemplate"
	// SandboxServiceDeleteSandboxTemplateProcedure is the fully-qualified name of the SandboxService's
	// DeleteSandboxTemplate RPC.
	SandboxServiceDeleteSandboxTemplateProcedure = "/retask.sandbox.v1.SandboxService/DeleteSandboxTemplate"
	// SandboxServiceGetSandboxActivitiesProcedure is the fully-qualified name of the SandboxService's
	// GetSandboxActivities RPC.
	SandboxServiceGetSandboxActivitiesProcedure = "/retask.sandbox.v1.SandboxService/GetSandboxActivities"
	// SandboxServiceGetSandboxUsageProcedure is the fully-qualified name of the SandboxService's
	// GetSandboxUsage RPC.
	SandboxServiceGetSandboxUsageProcedure = "/retask.sandbox.v1.SandboxService/GetSandboxUsage"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	sandboxServiceServiceDescriptor                     = v1.File_retask_sandbox_v1_sandbox_proto.Services().ByName("SandboxService")
	sandboxServiceGetSandboxesMethodDescriptor          = sandboxServiceServiceDescriptor.Methods().ByName("GetSandboxes")
	sandboxServiceGetSandboxMethodDescriptor            = sandboxServiceServiceDescriptor.Methods().ByName("GetSandbox")
	sandboxServiceGetSandboxRuntimeMethodDescriptor     = sandboxServiceServiceDescriptor.Methods().ByName("GetSandboxRuntime")
	sandboxServiceSetSandboxMethodDescriptor            = sandboxServiceServiceDescriptor.Methods().ByName("SetSandbox")
	sandboxServiceStopSandboxMethodDescriptor           = sandboxServiceServiceDescriptor.Methods().ByName("StopSandbox")
	sandboxServiceDeleteSandboxMethodDescriptor         = sandboxServiceServiceDescriptor.Methods().ByName("DeleteSandbox")
	sandboxServiceGetSessionsMethodDescriptor           = sandboxServiceServiceDescriptor.Methods().ByName("GetSessions")
	sandboxServiceGetSessionMethodDescriptor            = sandboxServiceServiceDescriptor.Methods().ByName("GetSession")
	sandboxServiceNewSessionMethodDescriptor            = sandboxServiceServiceDescriptor.Methods().ByName("NewSession")
	sandboxServiceSetPartialSessionMethodDescriptor     = sandboxServiceServiceDescriptor.Methods().ByName("SetPartialSession")
	sandboxServiceConnectSessionMethodDescriptor        = sandboxServiceServiceDescriptor.Methods().ByName("ConnectSession")
	sandboxServiceGetSessionRuntimeMethodDescriptor     = sandboxServiceServiceDescriptor.Methods().ByName("GetSessionRuntime")
	sandboxServiceStopSessionMethodDescriptor           = sandboxServiceServiceDescriptor.Methods().ByName("StopSession")
	sandboxServiceDeleteSessionMethodDescriptor         = sandboxServiceServiceDescriptor.Methods().ByName("DeleteSession")
	sandboxServiceReportSessionStatusMethodDescriptor   = sandboxServiceServiceDescriptor.Methods().ByName("ReportSessionStatus")
	sandboxServiceReportSandboxStatusMethodDescriptor   = sandboxServiceServiceDescriptor.Methods().ByName("ReportSandboxStatus")
	sandboxServiceGetSandboxTemplatesMethodDescriptor   = sandboxServiceServiceDescriptor.Methods().ByName("GetSandboxTemplates")
	sandboxServiceGetSandboxTemplateMethodDescriptor    = sandboxServiceServiceDescriptor.Methods().ByName("GetSandboxTemplate")
	sandboxServiceSetSandboxTemplateMethodDescriptor    = sandboxServiceServiceDescriptor.Methods().ByName("SetSandboxTemplate")
	sandboxServiceDeleteSandboxTemplateMethodDescriptor = sandboxServiceServiceDescriptor.Methods().ByName("DeleteSandboxTemplate")
	sandboxServiceGetSandboxActivitiesMethodDescriptor  = sandboxServiceServiceDescriptor.Methods().ByName("GetSandboxActivities")
	sandboxServiceGetSandboxUsageMethodDescriptor       = sandboxServiceServiceDescriptor.Methods().ByName("GetSandboxUsage")
)

// SandboxServiceClient is a client for the retask.sandbox.v1.SandboxService service.
type SandboxServiceClient interface {
	// === Sandbox CRUD ===
	GetSandboxes(context.Context, *connect.Request[v1.SandboxesRequest]) (*connect.Response[v1.SandboxesResponse], error)
	GetSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Sandbox], error)
	// BE-BE only (service-token auth). Returns the sandbox with
	// Config.EnvVar.SecretValue.value re-injected from secret-manager.
	GetSandboxRuntime(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SandboxRuntime], error)
	SetSandbox(context.Context, *connect.Request[v1.Sandbox]) (*connect.Response[v11.Id], error)
	StopSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	DeleteSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// === Session ===
	GetSessions(context.Context, *connect.Request[v1.SessionsRequest]) (*connect.Response[v1.SessionsResponse], error)
	GetSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Session], error)
	NewSession(context.Context, *connect.Request[v1.NewSessionRequest]) (*connect.Response[v11.Id], error)
	SetPartialSession(context.Context, *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error)
	ConnectSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SessionConnectionResponse], error)
	// BE-BE only (service-token auth). Returns the materialized runtime
	// view for a session: the Session, its parent Sandbox, and
	// Sandbox.Config with secret plaintext re-injected into
	// EnvVar.SecretValue.value. The caller (sandbox proxy) is trusted
	// to have already validated end-user authorization via the one-time
	// connect token issued by ConnectSession.
	GetSessionRuntime(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SessionRuntime], error)
	StopSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	DeleteSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// BE-BE only (service-token auth). Called by proxy on any session status
	// transition. Triggers async LLM extraction on IDLE and VM shutdown
	// evaluation on TIMEOUT.
	ReportSessionStatus(context.Context, *connect.Request[v1.ReportSessionStatusRequest]) (*connect.Response[v11.Empty], error)
	// BE-BE only (service-token auth). Called by proxy on any sandbox status
	// transition.
	ReportSandboxStatus(context.Context, *connect.Request[v1.ReportSandboxStatusRequest]) (*connect.Response[v11.Empty], error)
	// === SandboxTemplate CRUD ===
	GetSandboxTemplates(context.Context, *connect.Request[v1.SandboxTemplatesRequest]) (*connect.Response[v1.SandboxTemplatesResponse], error)
	GetSandboxTemplate(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SandboxTemplate], error)
	SetSandboxTemplate(context.Context, *connect.Request[v1.SandboxTemplate]) (*connect.Response[v11.Id], error)
	DeleteSandboxTemplate(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// === Activity (read-only) ===
	GetSandboxActivities(context.Context, *connect.Request[v1.SandboxActivitiesRequest]) (*connect.Response[v1.SandboxActivitiesResponse], error)
	GetSandboxUsage(context.Context, *connect.Request[v1.SandboxUsageRequest]) (*connect.Response[v1.SandboxUsage], error)
}

// NewSandboxServiceClient constructs a client for the retask.sandbox.v1.SandboxService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSandboxServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SandboxServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &sandboxServiceClient{
		getSandboxes: connect.NewClient[v1.SandboxesRequest, v1.SandboxesResponse](
			httpClient,
			baseURL+SandboxServiceGetSandboxesProcedure,
			connect.WithSchema(sandboxServiceGetSandboxesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSandbox: connect.NewClient[v11.Id, v1.Sandbox](
			httpClient,
			baseURL+SandboxServiceGetSandboxProcedure,
			connect.WithSchema(sandboxServiceGetSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSandboxRuntime: connect.NewClient[v11.Id, v1.SandboxRuntime](
			httpClient,
			baseURL+SandboxServiceGetSandboxRuntimeProcedure,
			connect.WithSchema(sandboxServiceGetSandboxRuntimeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setSandbox: connect.NewClient[v1.Sandbox, v11.Id](
			httpClient,
			baseURL+SandboxServiceSetSandboxProcedure,
			connect.WithSchema(sandboxServiceSetSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		stopSandbox: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+SandboxServiceStopSandboxProcedure,
			connect.WithSchema(sandboxServiceStopSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteSandbox: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+SandboxServiceDeleteSandboxProcedure,
			connect.WithSchema(sandboxServiceDeleteSandboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSessions: connect.NewClient[v1.SessionsRequest, v1.SessionsResponse](
			httpClient,
			baseURL+SandboxServiceGetSessionsProcedure,
			connect.WithSchema(sandboxServiceGetSessionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v11.Id, v1.Session](
			httpClient,
			baseURL+SandboxServiceGetSessionProcedure,
			connect.WithSchema(sandboxServiceGetSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		newSession: connect.NewClient[v1.NewSessionRequest, v11.Id](
			httpClient,
			baseURL+SandboxServiceNewSessionProcedure,
			connect.WithSchema(sandboxServiceNewSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setPartialSession: connect.NewClient[v11.PartialData, v11.Id](
			httpClient,
			baseURL+SandboxServiceSetPartialSessionProcedure,
			connect.WithSchema(sandboxServiceSetPartialSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		connectSession: connect.NewClient[v11.Id, v1.SessionConnectionResponse](
			httpClient,
			baseURL+SandboxServiceConnectSessionProcedure,
			connect.WithSchema(sandboxServiceConnectSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSessionRuntime: connect.NewClient[v11.Id, v1.SessionRuntime](
			httpClient,
			baseURL+SandboxServiceGetSessionRuntimeProcedure,
			connect.WithSchema(sandboxServiceGetSessionRuntimeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		stopSession: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+SandboxServiceStopSessionProcedure,
			connect.WithSchema(sandboxServiceStopSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+SandboxServiceDeleteSessionProcedure,
			connect.WithSchema(sandboxServiceDeleteSessionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		reportSessionStatus: connect.NewClient[v1.ReportSessionStatusRequest, v11.Empty](
			httpClient,
			baseURL+SandboxServiceReportSessionStatusProcedure,
			connect.WithSchema(sandboxServiceReportSessionStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		reportSandboxStatus: connect.NewClient[v1.ReportSandboxStatusRequest, v11.Empty](
			httpClient,
			baseURL+SandboxServiceReportSandboxStatusProcedure,
			connect.WithSchema(sandboxServiceReportSandboxStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSandboxTemplates: connect.NewClient[v1.SandboxTemplatesRequest, v1.SandboxTemplatesResponse](
			httpClient,
			baseURL+SandboxServiceGetSandboxTemplatesProcedure,
			connect.WithSchema(sandboxServiceGetSandboxTemplatesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSandboxTemplate: connect.NewClient[v11.Id, v1.SandboxTemplate](
			httpClient,
			baseURL+SandboxServiceGetSandboxTemplateProcedure,
			connect.WithSchema(sandboxServiceGetSandboxTemplateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setSandboxTemplate: connect.NewClient[v1.SandboxTemplate, v11.Id](
			httpClient,
			baseURL+SandboxServiceSetSandboxTemplateProcedure,
			connect.WithSchema(sandboxServiceSetSandboxTemplateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteSandboxTemplate: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+SandboxServiceDeleteSandboxTemplateProcedure,
			connect.WithSchema(sandboxServiceDeleteSandboxTemplateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSandboxActivities: connect.NewClient[v1.SandboxActivitiesRequest, v1.SandboxActivitiesResponse](
			httpClient,
			baseURL+SandboxServiceGetSandboxActivitiesProcedure,
			connect.WithSchema(sandboxServiceGetSandboxActivitiesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSandboxUsage: connect.NewClient[v1.SandboxUsageRequest, v1.SandboxUsage](
			httpClient,
			baseURL+SandboxServiceGetSandboxUsageProcedure,
			connect.WithSchema(sandboxServiceGetSandboxUsageMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// sandboxServiceClient implements SandboxServiceClient.
type sandboxServiceClient struct {
	getSandboxes          *connect.Client[v1.SandboxesRequest, v1.SandboxesResponse]
	getSandbox            *connect.Client[v11.Id, v1.Sandbox]
	getSandboxRuntime     *connect.Client[v11.Id, v1.SandboxRuntime]
	setSandbox            *connect.Client[v1.Sandbox, v11.Id]
	stopSandbox           *connect.Client[v11.Id, v11.Empty]
	deleteSandbox         *connect.Client[v11.Id, v11.Empty]
	getSessions           *connect.Client[v1.SessionsRequest, v1.SessionsResponse]
	getSession            *connect.Client[v11.Id, v1.Session]
	newSession            *connect.Client[v1.NewSessionRequest, v11.Id]
	setPartialSession     *connect.Client[v11.PartialData, v11.Id]
	connectSession        *connect.Client[v11.Id, v1.SessionConnectionResponse]
	getSessionRuntime     *connect.Client[v11.Id, v1.SessionRuntime]
	stopSession           *connect.Client[v11.Id, v11.Empty]
	deleteSession         *connect.Client[v11.Id, v11.Empty]
	reportSessionStatus   *connect.Client[v1.ReportSessionStatusRequest, v11.Empty]
	reportSandboxStatus   *connect.Client[v1.ReportSandboxStatusRequest, v11.Empty]
	getSandboxTemplates   *connect.Client[v1.SandboxTemplatesRequest, v1.SandboxTemplatesResponse]
	getSandboxTemplate    *connect.Client[v11.Id, v1.SandboxTemplate]
	setSandboxTemplate    *connect.Client[v1.SandboxTemplate, v11.Id]
	deleteSandboxTemplate *connect.Client[v11.Id, v11.Empty]
	getSandboxActivities  *connect.Client[v1.SandboxActivitiesRequest, v1.SandboxActivitiesResponse]
	getSandboxUsage       *connect.Client[v1.SandboxUsageRequest, v1.SandboxUsage]
}

// GetSandboxes calls retask.sandbox.v1.SandboxService.GetSandboxes.
func (c *sandboxServiceClient) GetSandboxes(ctx context.Context, req *connect.Request[v1.SandboxesRequest]) (*connect.Response[v1.SandboxesResponse], error) {
	return c.getSandboxes.CallUnary(ctx, req)
}

// GetSandbox calls retask.sandbox.v1.SandboxService.GetSandbox.
func (c *sandboxServiceClient) GetSandbox(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.Sandbox], error) {
	return c.getSandbox.CallUnary(ctx, req)
}

// GetSandboxRuntime calls retask.sandbox.v1.SandboxService.GetSandboxRuntime.
func (c *sandboxServiceClient) GetSandboxRuntime(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.SandboxRuntime], error) {
	return c.getSandboxRuntime.CallUnary(ctx, req)
}

// SetSandbox calls retask.sandbox.v1.SandboxService.SetSandbox.
func (c *sandboxServiceClient) SetSandbox(ctx context.Context, req *connect.Request[v1.Sandbox]) (*connect.Response[v11.Id], error) {
	return c.setSandbox.CallUnary(ctx, req)
}

// StopSandbox calls retask.sandbox.v1.SandboxService.StopSandbox.
func (c *sandboxServiceClient) StopSandbox(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.stopSandbox.CallUnary(ctx, req)
}

// DeleteSandbox calls retask.sandbox.v1.SandboxService.DeleteSandbox.
func (c *sandboxServiceClient) DeleteSandbox(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteSandbox.CallUnary(ctx, req)
}

// GetSessions calls retask.sandbox.v1.SandboxService.GetSessions.
func (c *sandboxServiceClient) GetSessions(ctx context.Context, req *connect.Request[v1.SessionsRequest]) (*connect.Response[v1.SessionsResponse], error) {
	return c.getSessions.CallUnary(ctx, req)
}

// GetSession calls retask.sandbox.v1.SandboxService.GetSession.
func (c *sandboxServiceClient) GetSession(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.Session], error) {
	return c.getSession.CallUnary(ctx, req)
}

// NewSession calls retask.sandbox.v1.SandboxService.NewSession.
func (c *sandboxServiceClient) NewSession(ctx context.Context, req *connect.Request[v1.NewSessionRequest]) (*connect.Response[v11.Id], error) {
	return c.newSession.CallUnary(ctx, req)
}

// SetPartialSession calls retask.sandbox.v1.SandboxService.SetPartialSession.
func (c *sandboxServiceClient) SetPartialSession(ctx context.Context, req *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error) {
	return c.setPartialSession.CallUnary(ctx, req)
}

// ConnectSession calls retask.sandbox.v1.SandboxService.ConnectSession.
func (c *sandboxServiceClient) ConnectSession(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.SessionConnectionResponse], error) {
	return c.connectSession.CallUnary(ctx, req)
}

// GetSessionRuntime calls retask.sandbox.v1.SandboxService.GetSessionRuntime.
func (c *sandboxServiceClient) GetSessionRuntime(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.SessionRuntime], error) {
	return c.getSessionRuntime.CallUnary(ctx, req)
}

// StopSession calls retask.sandbox.v1.SandboxService.StopSession.
func (c *sandboxServiceClient) StopSession(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.stopSession.CallUnary(ctx, req)
}

// DeleteSession calls retask.sandbox.v1.SandboxService.DeleteSession.
func (c *sandboxServiceClient) DeleteSession(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteSession.CallUnary(ctx, req)
}

// ReportSessionStatus calls retask.sandbox.v1.SandboxService.ReportSessionStatus.
func (c *sandboxServiceClient) ReportSessionStatus(ctx context.Context, req *connect.Request[v1.ReportSessionStatusRequest]) (*connect.Response[v11.Empty], error) {
	return c.reportSessionStatus.CallUnary(ctx, req)
}

// ReportSandboxStatus calls retask.sandbox.v1.SandboxService.ReportSandboxStatus.
func (c *sandboxServiceClient) ReportSandboxStatus(ctx context.Context, req *connect.Request[v1.ReportSandboxStatusRequest]) (*connect.Response[v11.Empty], error) {
	return c.reportSandboxStatus.CallUnary(ctx, req)
}

// GetSandboxTemplates calls retask.sandbox.v1.SandboxService.GetSandboxTemplates.
func (c *sandboxServiceClient) GetSandboxTemplates(ctx context.Context, req *connect.Request[v1.SandboxTemplatesRequest]) (*connect.Response[v1.SandboxTemplatesResponse], error) {
	return c.getSandboxTemplates.CallUnary(ctx, req)
}

// GetSandboxTemplate calls retask.sandbox.v1.SandboxService.GetSandboxTemplate.
func (c *sandboxServiceClient) GetSandboxTemplate(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.SandboxTemplate], error) {
	return c.getSandboxTemplate.CallUnary(ctx, req)
}

// SetSandboxTemplate calls retask.sandbox.v1.SandboxService.SetSandboxTemplate.
func (c *sandboxServiceClient) SetSandboxTemplate(ctx context.Context, req *connect.Request[v1.SandboxTemplate]) (*connect.Response[v11.Id], error) {
	return c.setSandboxTemplate.CallUnary(ctx, req)
}

// DeleteSandboxTemplate calls retask.sandbox.v1.SandboxService.DeleteSandboxTemplate.
func (c *sandboxServiceClient) DeleteSandboxTemplate(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteSandboxTemplate.CallUnary(ctx, req)
}

// GetSandboxActivities calls retask.sandbox.v1.SandboxService.GetSandboxActivities.
func (c *sandboxServiceClient) GetSandboxActivities(ctx context.Context, req *connect.Request[v1.SandboxActivitiesRequest]) (*connect.Response[v1.SandboxActivitiesResponse], error) {
	return c.getSandboxActivities.CallUnary(ctx, req)
}

// GetSandboxUsage calls retask.sandbox.v1.SandboxService.GetSandboxUsage.
func (c *sandboxServiceClient) GetSandboxUsage(ctx context.Context, req *connect.Request[v1.SandboxUsageRequest]) (*connect.Response[v1.SandboxUsage], error) {
	return c.getSandboxUsage.CallUnary(ctx, req)
}

// SandboxServiceHandler is an implementation of the retask.sandbox.v1.SandboxService service.
type SandboxServiceHandler interface {
	// === Sandbox CRUD ===
	GetSandboxes(context.Context, *connect.Request[v1.SandboxesRequest]) (*connect.Response[v1.SandboxesResponse], error)
	GetSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Sandbox], error)
	// BE-BE only (service-token auth). Returns the sandbox with
	// Config.EnvVar.SecretValue.value re-injected from secret-manager.
	GetSandboxRuntime(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SandboxRuntime], error)
	SetSandbox(context.Context, *connect.Request[v1.Sandbox]) (*connect.Response[v11.Id], error)
	StopSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	DeleteSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// === Session ===
	GetSessions(context.Context, *connect.Request[v1.SessionsRequest]) (*connect.Response[v1.SessionsResponse], error)
	GetSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Session], error)
	NewSession(context.Context, *connect.Request[v1.NewSessionRequest]) (*connect.Response[v11.Id], error)
	SetPartialSession(context.Context, *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error)
	ConnectSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SessionConnectionResponse], error)
	// BE-BE only (service-token auth). Returns the materialized runtime
	// view for a session: the Session, its parent Sandbox, and
	// Sandbox.Config with secret plaintext re-injected into
	// EnvVar.SecretValue.value. The caller (sandbox proxy) is trusted
	// to have already validated end-user authorization via the one-time
	// connect token issued by ConnectSession.
	GetSessionRuntime(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SessionRuntime], error)
	StopSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	DeleteSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// BE-BE only (service-token auth). Called by proxy on any session status
	// transition. Triggers async LLM extraction on IDLE and VM shutdown
	// evaluation on TIMEOUT.
	ReportSessionStatus(context.Context, *connect.Request[v1.ReportSessionStatusRequest]) (*connect.Response[v11.Empty], error)
	// BE-BE only (service-token auth). Called by proxy on any sandbox status
	// transition.
	ReportSandboxStatus(context.Context, *connect.Request[v1.ReportSandboxStatusRequest]) (*connect.Response[v11.Empty], error)
	// === SandboxTemplate CRUD ===
	GetSandboxTemplates(context.Context, *connect.Request[v1.SandboxTemplatesRequest]) (*connect.Response[v1.SandboxTemplatesResponse], error)
	GetSandboxTemplate(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SandboxTemplate], error)
	SetSandboxTemplate(context.Context, *connect.Request[v1.SandboxTemplate]) (*connect.Response[v11.Id], error)
	DeleteSandboxTemplate(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// === Activity (read-only) ===
	GetSandboxActivities(context.Context, *connect.Request[v1.SandboxActivitiesRequest]) (*connect.Response[v1.SandboxActivitiesResponse], error)
	GetSandboxUsage(context.Context, *connect.Request[v1.SandboxUsageRequest]) (*connect.Response[v1.SandboxUsage], error)
}

// NewSandboxServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSandboxServiceHandler(svc SandboxServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sandboxServiceGetSandboxesHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxesProcedure,
		svc.GetSandboxes,
		connect.WithSchema(sandboxServiceGetSandboxesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSandboxHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxProcedure,
		svc.GetSandbox,
		connect.WithSchema(sandboxServiceGetSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSandboxRuntimeHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxRuntimeProcedure,
		svc.GetSandboxRuntime,
		connect.WithSchema(sandboxServiceGetSandboxRuntimeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceSetSandboxHandler := connect.NewUnaryHandler(
		SandboxServiceSetSandboxProcedure,
		svc.SetSandbox,
		connect.WithSchema(sandboxServiceSetSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceStopSandboxHandler := connect.NewUnaryHandler(
		SandboxServiceStopSandboxProcedure,
		svc.StopSandbox,
		connect.WithSchema(sandboxServiceStopSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceDeleteSandboxHandler := connect.NewUnaryHandler(
		SandboxServiceDeleteSandboxProcedure,
		svc.DeleteSandbox,
		connect.WithSchema(sandboxServiceDeleteSandboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSessionsHandler := connect.NewUnaryHandler(
		SandboxServiceGetSessionsProcedure,
		svc.GetSessions,
		connect.WithSchema(sandboxServiceGetSessionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSessionHandler := connect.NewUnaryHandler(
		SandboxServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(sandboxServiceGetSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceNewSessionHandler := connect.NewUnaryHandler(
		SandboxServiceNewSessionProcedure,
		svc.NewSession,
		connect.WithSchema(sandboxServiceNewSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceSetPartialSessionHandler := connect.NewUnaryHandler(
		SandboxServiceSetPartialSessionProcedure,
		svc.SetPartialSession,
		connect.WithSchema(sandboxServiceSetPartialSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceConnectSessionHandler := connect.NewUnaryHandler(
		SandboxServiceConnectSessionProcedure,
		svc.ConnectSession,
		connect.WithSchema(sandboxServiceConnectSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSessionRuntimeHandler := connect.NewUnaryHandler(
		SandboxServiceGetSessionRuntimeProcedure,
		svc.GetSessionRuntime,
		connect.WithSchema(sandboxServiceGetSessionRuntimeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceStopSessionHandler := connect.NewUnaryHandler(
		SandboxServiceStopSessionProcedure,
		svc.StopSession,
		connect.WithSchema(sandboxServiceStopSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceDeleteSessionHandler := connect.NewUnaryHandler(
		SandboxServiceDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(sandboxServiceDeleteSessionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceReportSessionStatusHandler := connect.NewUnaryHandler(
		SandboxServiceReportSessionStatusProcedure,
		svc.ReportSessionStatus,
		connect.WithSchema(sandboxServiceReportSessionStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceReportSandboxStatusHandler := connect.NewUnaryHandler(
		SandboxServiceReportSandboxStatusProcedure,
		svc.ReportSandboxStatus,
		connect.WithSchema(sandboxServiceReportSandboxStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSandboxTemplatesHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxTemplatesProcedure,
		svc.GetSandboxTemplates,
		connect.WithSchema(sandboxServiceGetSandboxTemplatesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSandboxTemplateHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxTemplateProcedure,
		svc.GetSandboxTemplate,
		connect.WithSchema(sandboxServiceGetSandboxTemplateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceSetSandboxTemplateHandler := connect.NewUnaryHandler(
		SandboxServiceSetSandboxTemplateProcedure,
		svc.SetSandboxTemplate,
		connect.WithSchema(sandboxServiceSetSandboxTemplateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceDeleteSandboxTemplateHandler := connect.NewUnaryHandler(
		SandboxServiceDeleteSandboxTemplateProcedure,
		svc.DeleteSandboxTemplate,
		connect.WithSchema(sandboxServiceDeleteSandboxTemplateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSandboxActivitiesHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxActivitiesProcedure,
		svc.GetSandboxActivities,
		connect.WithSchema(sandboxServiceGetSandboxActivitiesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSandboxUsageHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxUsageProcedure,
		svc.GetSandboxUsage,
		connect.WithSchema(sandboxServiceGetSandboxUsageMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/retask.sandbox.v1.SandboxService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SandboxServiceGetSandboxesProcedure:
			sandboxServiceGetSandboxesHandler.ServeHTTP(w, r)
		case SandboxServiceGetSandboxProcedure:
			sandboxServiceGetSandboxHandler.ServeHTTP(w, r)
		case SandboxServiceGetSandboxRuntimeProcedure:
			sandboxServiceGetSandboxRuntimeHandler.ServeHTTP(w, r)
		case SandboxServiceSetSandboxProcedure:
			sandboxServiceSetSandboxHandler.ServeHTTP(w, r)
		case SandboxServiceStopSandboxProcedure:
			sandboxServiceStopSandboxHandler.ServeHTTP(w, r)
		case SandboxServiceDeleteSandboxProcedure:
			sandboxServiceDeleteSandboxHandler.ServeHTTP(w, r)
		case SandboxServiceGetSessionsProcedure:
			sandboxServiceGetSessionsHandler.ServeHTTP(w, r)
		case SandboxServiceGetSessionProcedure:
			sandboxServiceGetSessionHandler.ServeHTTP(w, r)
		case SandboxServiceNewSessionProcedure:
			sandboxServiceNewSessionHandler.ServeHTTP(w, r)
		case SandboxServiceSetPartialSessionProcedure:
			sandboxServiceSetPartialSessionHandler.ServeHTTP(w, r)
		case SandboxServiceConnectSessionProcedure:
			sandboxServiceConnectSessionHandler.ServeHTTP(w, r)
		case SandboxServiceGetSessionRuntimeProcedure:
			sandboxServiceGetSessionRuntimeHandler.ServeHTTP(w, r)
		case SandboxServiceStopSessionProcedure:
			sandboxServiceStopSessionHandler.ServeHTTP(w, r)
		case SandboxServiceDeleteSessionProcedure:
			sandboxServiceDeleteSessionHandler.ServeHTTP(w, r)
		case SandboxServiceReportSessionStatusProcedure:
			sandboxServiceReportSessionStatusHandler.ServeHTTP(w, r)
		case SandboxServiceReportSandboxStatusProcedure:
			sandboxServiceReportSandboxStatusHandler.ServeHTTP(w, r)
		case SandboxServiceGetSandboxTemplatesProcedure:
			sandboxServiceGetSandboxTemplatesHandler.ServeHTTP(w, r)
		case SandboxServiceGetSandboxTemplateProcedure:
			sandboxServiceGetSandboxTemplateHandler.ServeHTTP(w, r)
		case SandboxServiceSetSandboxTemplateProcedure:
			sandboxServiceSetSandboxTemplateHandler.ServeHTTP(w, r)
		case SandboxServiceDeleteSandboxTemplateProcedure:
			sandboxServiceDeleteSandboxTemplateHandler.ServeHTTP(w, r)
		case SandboxServiceGetSandboxActivitiesProcedure:
			sandboxServiceGetSandboxActivitiesHandler.ServeHTTP(w, r)
		case SandboxServiceGetSandboxUsageProcedure:
			sandboxServiceGetSandboxUsageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSandboxServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSandboxServiceHandler struct{}

func (UnimplementedSandboxServiceHandler) GetSandboxes(context.Context, *connect.Request[v1.SandboxesRequest]) (*connect.Response[v1.SandboxesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSandboxes is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Sandbox], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSandbox is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSandboxRuntime(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SandboxRuntime], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSandboxRuntime is not implemented"))
}

func (UnimplementedSandboxServiceHandler) SetSandbox(context.Context, *connect.Request[v1.Sandbox]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.SetSandbox is not implemented"))
}

func (UnimplementedSandboxServiceHandler) StopSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.StopSandbox is not implemented"))
}

func (UnimplementedSandboxServiceHandler) DeleteSandbox(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.DeleteSandbox is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSessions(context.Context, *connect.Request[v1.SessionsRequest]) (*connect.Response[v1.SessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSessions is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSession is not implemented"))
}

func (UnimplementedSandboxServiceHandler) NewSession(context.Context, *connect.Request[v1.NewSessionRequest]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.NewSession is not implemented"))
}

func (UnimplementedSandboxServiceHandler) SetPartialSession(context.Context, *connect.Request[v11.PartialData]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.SetPartialSession is not implemented"))
}

func (UnimplementedSandboxServiceHandler) ConnectSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SessionConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.ConnectSession is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSessionRuntime(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SessionRuntime], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSessionRuntime is not implemented"))
}

func (UnimplementedSandboxServiceHandler) StopSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.StopSession is not implemented"))
}

func (UnimplementedSandboxServiceHandler) DeleteSession(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.DeleteSession is not implemented"))
}

func (UnimplementedSandboxServiceHandler) ReportSessionStatus(context.Context, *connect.Request[v1.ReportSessionStatusRequest]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.ReportSessionStatus is not implemented"))
}

func (UnimplementedSandboxServiceHandler) ReportSandboxStatus(context.Context, *connect.Request[v1.ReportSandboxStatusRequest]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.ReportSandboxStatus is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSandboxTemplates(context.Context, *connect.Request[v1.SandboxTemplatesRequest]) (*connect.Response[v1.SandboxTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSandboxTemplates is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSandboxTemplate(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.SandboxTemplate], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSandboxTemplate is not implemented"))
}

func (UnimplementedSandboxServiceHandler) SetSandboxTemplate(context.Context, *connect.Request[v1.SandboxTemplate]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.SetSandboxTemplate is not implemented"))
}

func (UnimplementedSandboxServiceHandler) DeleteSandboxTemplate(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.DeleteSandboxTemplate is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSandboxActivities(context.Context, *connect.Request[v1.SandboxActivitiesRequest]) (*connect.Response[v1.SandboxActivitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSandboxActivities is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSandboxUsage(context.Context, *connect.Request[v1.SandboxUsageRequest]) (*connect.Response[v1.SandboxUsage], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.sandbox.v1.SandboxService.GetSandboxUsage is not implemented"))
}
