// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: retask/task/v1/task.proto

package taskv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "nweb.xyz/retask-cli/proto-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TaskService_GetTasks_FullMethodName             = "/retask.task.v1.TaskService/GetTasks"
	TaskService_GetTask_FullMethodName              = "/retask.task.v1.TaskService/GetTask"
	TaskService_GetTaskByKey_FullMethodName         = "/retask.task.v1.TaskService/GetTaskByKey"
	TaskService_SetTask_FullMethodName              = "/retask.task.v1.TaskService/SetTask"
	TaskService_DeleteTask_FullMethodName           = "/retask.task.v1.TaskService/DeleteTask"
	TaskService_SetPartialTask_FullMethodName       = "/retask.task.v1.TaskService/SetPartialTask"
	TaskService_AddTaskAttachment_FullMethodName    = "/retask.task.v1.TaskService/AddTaskAttachment"
	TaskService_DeleteTaskAttachment_FullMethodName = "/retask.task.v1.TaskService/DeleteTaskAttachment"
	TaskService_GetTasksUsage_FullMethodName        = "/retask.task.v1.TaskService/GetTasksUsage"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	GetTasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (*TasksResponse, error)
	GetTask(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Task, error)
	GetTaskByKey(ctx context.Context, in *TaskByKeyRequest, opts ...grpc.CallOption) (*Task, error)
	SetTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*v1.Id, error)
	DeleteTask(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	SetPartialTask(ctx context.Context, in *v1.PartialData, opts ...grpc.CallOption) (*v1.Id, error)
	AddTaskAttachment(ctx context.Context, in *AddTaskAttachmentRequest, opts ...grpc.CallOption) (*Task, error)
	DeleteTaskAttachment(ctx context.Context, in *DeleteTaskAttachmentRequest, opts ...grpc.CallOption) (*Task, error)
	GetTasksUsage(ctx context.Context, in *TasksUsageRequest, opts ...grpc.CallOption) (*TasksUsage, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetTasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (*TasksResponse, error) {
	out := new(TasksResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_GetTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskByKey(ctx context.Context, in *TaskByKeyRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_GetTaskByKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SetTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, TaskService_SetTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, TaskService_DeleteTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SetPartialTask(ctx context.Context, in *v1.PartialData, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, TaskService_SetPartialTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) AddTaskAttachment(ctx context.Context, in *AddTaskAttachmentRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_AddTaskAttachment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTaskAttachment(ctx context.Context, in *DeleteTaskAttachmentRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_DeleteTaskAttachment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTasksUsage(ctx context.Context, in *TasksUsageRequest, opts ...grpc.CallOption) (*TasksUsage, error) {
	out := new(TasksUsage)
	err := c.cc.Invoke(ctx, TaskService_GetTasksUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility
type TaskServiceServer interface {
	GetTasks(context.Context, *TasksRequest) (*TasksResponse, error)
	GetTask(context.Context, *v1.Id) (*Task, error)
	GetTaskByKey(context.Context, *TaskByKeyRequest) (*Task, error)
	SetTask(context.Context, *Task) (*v1.Id, error)
	DeleteTask(context.Context, *v1.Id) (*v1.Empty, error)
	SetPartialTask(context.Context, *v1.PartialData) (*v1.Id, error)
	AddTaskAttachment(context.Context, *AddTaskAttachmentRequest) (*Task, error)
	DeleteTaskAttachment(context.Context, *DeleteTaskAttachmentRequest) (*Task, error)
	GetTasksUsage(context.Context, *TasksUsageRequest) (*TasksUsage, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (UnimplementedTaskServiceServer) GetTasks(context.Context, *TasksRequest) (*TasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedTaskServiceServer) GetTask(context.Context, *v1.Id) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServiceServer) GetTaskByKey(context.Context, *TaskByKeyRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskByKey not implemented")
}
func (UnimplementedTaskServiceServer) SetTask(context.Context, *Task) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTask not implemented")
}
func (UnimplementedTaskServiceServer) DeleteTask(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskServiceServer) SetPartialTask(context.Context, *v1.PartialData) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPartialTask not implemented")
}
func (UnimplementedTaskServiceServer) AddTaskAttachment(context.Context, *AddTaskAttachmentRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTaskAttachment not implemented")
}
func (UnimplementedTaskServiceServer) DeleteTaskAttachment(context.Context, *DeleteTaskAttachmentRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTaskAttachment not implemented")
}
func (UnimplementedTaskServiceServer) GetTasksUsage(context.Context, *TasksUsageRequest) (*TasksUsage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasksUsage not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTasks(ctx, req.(*TasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTaskByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskByKey(ctx, req.(*TaskByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SetTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SetPartialTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PartialData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SetPartialTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SetPartialTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SetPartialTask(ctx, req.(*v1.PartialData))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_AddTaskAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AddTaskAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_AddTaskAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AddTaskAttachment(ctx, req.(*AddTaskAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTaskAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTaskAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteTaskAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTaskAttachment(ctx, req.(*DeleteTaskAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTasksUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTasksUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTasksUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTasksUsage(ctx, req.(*TasksUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "retask.task.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTasks",
			Handler:    _TaskService_GetTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "GetTaskByKey",
			Handler:    _TaskService_GetTaskByKey_Handler,
		},
		{
			MethodName: "SetTask",
			Handler:    _TaskService_SetTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
		{
			MethodName: "SetPartialTask",
			Handler:    _TaskService_SetPartialTask_Handler,
		},
		{
			MethodName: "AddTaskAttachment",
			Handler:    _TaskService_AddTaskAttachment_Handler,
		},
		{
			MethodName: "DeleteTaskAttachment",
			Handler:    _TaskService_DeleteTaskAttachment_Handler,
		},
		{
			MethodName: "GetTasksUsage",
			Handler:    _TaskService_GetTasksUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retask/task/v1/task.proto",
}
