// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: integration/v1/integration.proto

package integrationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IntegrationService_GetProviders_FullMethodName      = "/integration.v1.IntegrationService/GetProviders"
	IntegrationService_GetProvider_FullMethodName       = "/integration.v1.IntegrationService/GetProvider"
	IntegrationService_GetIntegrations_FullMethodName   = "/integration.v1.IntegrationService/GetIntegrations"
	IntegrationService_GetIntegration_FullMethodName    = "/integration.v1.IntegrationService/GetIntegration"
	IntegrationService_SetIntegration_FullMethodName    = "/integration.v1.IntegrationService/SetIntegration"
	IntegrationService_DeleteIntegration_FullMethodName = "/integration.v1.IntegrationService/DeleteIntegration"
	IntegrationService_AccessIntegration_FullMethodName = "/integration.v1.IntegrationService/AccessIntegration"
	IntegrationService_GetGithubRepos_FullMethodName    = "/integration.v1.IntegrationService/GetGithubRepos"
)

// IntegrationServiceClient is the client API for IntegrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrationServiceClient interface {
	GetProviders(ctx context.Context, in *ProvidersRequest, opts ...grpc.CallOption) (*ProvidersResponse, error)
	GetProvider(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Provider, error)
	GetIntegrations(ctx context.Context, in *IntegrationsRequest, opts ...grpc.CallOption) (*IntegrationsResponse, error)
	GetIntegration(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Integration, error)
	// Create or update. Uniqueness on (workspace_id, provider_id, level,
	// owner_member_id): a second call for the same tuple replaces the
	// existing row and rotates the underlying secrets.
	SetIntegration(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*v1.Id, error)
	// Hard delete. Removes the Integration row and emits IntegrationDeleted;
	// secret-manager listens and hard-deletes the underlying token secrets.
	DeleteIntegration(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	// Resolves the right Integration for (workspace, provider, caller) and
	// returns plaintext credentials via secret-manager.
	// Resolution order: MEMBER (caller's user_nrn from gRPC metadata →
	// workspace_member_id) then WORKSPACE fallback.
	// Errors:
	//
	//	NOT_FOUND           — neither MEMBER nor WORKSPACE integration exists.
	//	FAILED_PRECONDITION — resolved integration's expires_at is past.
	AccessIntegration(ctx context.Context, in *AccessIntegrationRequest, opts ...grpc.CallOption) (*AccessIntegrationResponse, error)
	// Resolves the caller's GitHub integration and returns the repo catalog.
	// If level is set, uses that integration exactly; otherwise defaults to
	// MEMBER-first with WORKSPACE fallback. The raw token is never returned.
	GetGithubRepos(ctx context.Context, in *GithubReposRequest, opts ...grpc.CallOption) (*GithubReposResponse, error)
}

type integrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationServiceClient(cc grpc.ClientConnInterface) IntegrationServiceClient {
	return &integrationServiceClient{cc}
}

func (c *integrationServiceClient) GetProviders(ctx context.Context, in *ProvidersRequest, opts ...grpc.CallOption) (*ProvidersResponse, error) {
	out := new(ProvidersResponse)
	err := c.cc.Invoke(ctx, IntegrationService_GetProviders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) GetProvider(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Provider, error) {
	out := new(Provider)
	err := c.cc.Invoke(ctx, IntegrationService_GetProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) GetIntegrations(ctx context.Context, in *IntegrationsRequest, opts ...grpc.CallOption) (*IntegrationsResponse, error) {
	out := new(IntegrationsResponse)
	err := c.cc.Invoke(ctx, IntegrationService_GetIntegrations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) GetIntegration(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Integration, error) {
	out := new(Integration)
	err := c.cc.Invoke(ctx, IntegrationService_GetIntegration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) SetIntegration(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, IntegrationService_SetIntegration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) DeleteIntegration(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, IntegrationService_DeleteIntegration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) AccessIntegration(ctx context.Context, in *AccessIntegrationRequest, opts ...grpc.CallOption) (*AccessIntegrationResponse, error) {
	out := new(AccessIntegrationResponse)
	err := c.cc.Invoke(ctx, IntegrationService_AccessIntegration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) GetGithubRepos(ctx context.Context, in *GithubReposRequest, opts ...grpc.CallOption) (*GithubReposResponse, error) {
	out := new(GithubReposResponse)
	err := c.cc.Invoke(ctx, IntegrationService_GetGithubRepos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationServiceServer is the server API for IntegrationService service.
// All implementations must embed UnimplementedIntegrationServiceServer
// for forward compatibility
type IntegrationServiceServer interface {
	GetProviders(context.Context, *ProvidersRequest) (*ProvidersResponse, error)
	GetProvider(context.Context, *v1.Id) (*Provider, error)
	GetIntegrations(context.Context, *IntegrationsRequest) (*IntegrationsResponse, error)
	GetIntegration(context.Context, *v1.Id) (*Integration, error)
	// Create or update. Uniqueness on (workspace_id, provider_id, level,
	// owner_member_id): a second call for the same tuple replaces the
	// existing row and rotates the underlying secrets.
	SetIntegration(context.Context, *Integration) (*v1.Id, error)
	// Hard delete. Removes the Integration row and emits IntegrationDeleted;
	// secret-manager listens and hard-deletes the underlying token secrets.
	DeleteIntegration(context.Context, *v1.Id) (*v1.Empty, error)
	// Resolves the right Integration for (workspace, provider, caller) and
	// returns plaintext credentials via secret-manager.
	// Resolution order: MEMBER (caller's user_nrn from gRPC metadata →
	// workspace_member_id) then WORKSPACE fallback.
	// Errors:
	//
	//	NOT_FOUND           — neither MEMBER nor WORKSPACE integration exists.
	//	FAILED_PRECONDITION — resolved integration's expires_at is past.
	AccessIntegration(context.Context, *AccessIntegrationRequest) (*AccessIntegrationResponse, error)
	// Resolves the caller's GitHub integration and returns the repo catalog.
	// If level is set, uses that integration exactly; otherwise defaults to
	// MEMBER-first with WORKSPACE fallback. The raw token is never returned.
	GetGithubRepos(context.Context, *GithubReposRequest) (*GithubReposResponse, error)
	mustEmbedUnimplementedIntegrationServiceServer()
}

// UnimplementedIntegrationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntegrationServiceServer struct {
}

func (UnimplementedIntegrationServiceServer) GetProviders(context.Context, *ProvidersRequest) (*ProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedIntegrationServiceServer) GetProvider(context.Context, *v1.Id) (*Provider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedIntegrationServiceServer) GetIntegrations(context.Context, *IntegrationsRequest) (*IntegrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrations not implemented")
}
func (UnimplementedIntegrationServiceServer) GetIntegration(context.Context, *v1.Id) (*Integration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegration not implemented")
}
func (UnimplementedIntegrationServiceServer) SetIntegration(context.Context, *Integration) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIntegration not implemented")
}
func (UnimplementedIntegrationServiceServer) DeleteIntegration(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIntegration not implemented")
}
func (UnimplementedIntegrationServiceServer) AccessIntegration(context.Context, *AccessIntegrationRequest) (*AccessIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessIntegration not implemented")
}
func (UnimplementedIntegrationServiceServer) GetGithubRepos(context.Context, *GithubReposRequest) (*GithubReposResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGithubRepos not implemented")
}
func (UnimplementedIntegrationServiceServer) mustEmbedUnimplementedIntegrationServiceServer() {}

// UnsafeIntegrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationServiceServer will
// result in compilation errors.
type UnsafeIntegrationServiceServer interface {
	mustEmbedUnimplementedIntegrationServiceServer()
}

func RegisterIntegrationServiceServer(s grpc.ServiceRegistrar, srv IntegrationServiceServer) {
	s.RegisterService(&IntegrationService_ServiceDesc, srv)
}

func _IntegrationService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).GetProviders(ctx, req.(*ProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).GetProvider(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_GetIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).GetIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_GetIntegrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).GetIntegrations(ctx, req.(*IntegrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_GetIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).GetIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_GetIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).GetIntegration(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_SetIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Integration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).SetIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_SetIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).SetIntegration(ctx, req.(*Integration))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_DeleteIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).DeleteIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_DeleteIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).DeleteIntegration(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_AccessIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).AccessIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_AccessIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).AccessIntegration(ctx, req.(*AccessIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_GetGithubRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GithubReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).GetGithubRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationService_GetGithubRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).GetGithubRepos(ctx, req.(*GithubReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrationService_ServiceDesc is the grpc.ServiceDesc for IntegrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integration.v1.IntegrationService",
	HandlerType: (*IntegrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProviders",
			Handler:    _IntegrationService_GetProviders_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _IntegrationService_GetProvider_Handler,
		},
		{
			MethodName: "GetIntegrations",
			Handler:    _IntegrationService_GetIntegrations_Handler,
		},
		{
			MethodName: "GetIntegration",
			Handler:    _IntegrationService_GetIntegration_Handler,
		},
		{
			MethodName: "SetIntegration",
			Handler:    _IntegrationService_SetIntegration_Handler,
		},
		{
			MethodName: "DeleteIntegration",
			Handler:    _IntegrationService_DeleteIntegration_Handler,
		},
		{
			MethodName: "AccessIntegration",
			Handler:    _IntegrationService_AccessIntegration_Handler,
		},
		{
			MethodName: "GetGithubRepos",
			Handler:    _IntegrationService_GetGithubRepos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integration/v1/integration.proto",
}
