// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: retask/agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/retask/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "retask.agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceGetAgentsProcedure is the fully-qualified name of the AgentService's GetAgents RPC.
	AgentServiceGetAgentsProcedure = "/retask.agent.v1.AgentService/GetAgents"
	// AgentServiceGetAgentProcedure is the fully-qualified name of the AgentService's GetAgent RPC.
	AgentServiceGetAgentProcedure = "/retask.agent.v1.AgentService/GetAgent"
	// AgentServiceSetAgentProcedure is the fully-qualified name of the AgentService's SetAgent RPC.
	AgentServiceSetAgentProcedure = "/retask.agent.v1.AgentService/SetAgent"
	// AgentServiceDeleteAgentProcedure is the fully-qualified name of the AgentService's DeleteAgent
	// RPC.
	AgentServiceDeleteAgentProcedure = "/retask.agent.v1.AgentService/DeleteAgent"
	// AgentServiceGetSuggestedAgentsProcedure is the fully-qualified name of the AgentService's
	// GetSuggestedAgents RPC.
	AgentServiceGetSuggestedAgentsProcedure = "/retask.agent.v1.AgentService/GetSuggestedAgents"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	agentServiceServiceDescriptor                  = v1.File_retask_agent_v1_agent_proto.Services().ByName("AgentService")
	agentServiceGetAgentsMethodDescriptor          = agentServiceServiceDescriptor.Methods().ByName("GetAgents")
	agentServiceGetAgentMethodDescriptor           = agentServiceServiceDescriptor.Methods().ByName("GetAgent")
	agentServiceSetAgentMethodDescriptor           = agentServiceServiceDescriptor.Methods().ByName("SetAgent")
	agentServiceDeleteAgentMethodDescriptor        = agentServiceServiceDescriptor.Methods().ByName("DeleteAgent")
	agentServiceGetSuggestedAgentsMethodDescriptor = agentServiceServiceDescriptor.Methods().ByName("GetSuggestedAgents")
)

// AgentServiceClient is a client for the retask.agent.v1.AgentService service.
type AgentServiceClient interface {
	// === Agent CRUD ===
	GetAgents(context.Context, *connect.Request[v1.AgentsRequest]) (*connect.Response[v1.AgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Agent], error)
	SetAgent(context.Context, *connect.Request[v1.Agent]) (*connect.Response[v11.Id], error)
	DeleteAgent(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// === Suggestions ===
	GetSuggestedAgents(context.Context, *connect.Request[v1.SuggestedAgentsRequest]) (*connect.Response[v1.SuggestedAgentsResponse], error)
}

// NewAgentServiceClient constructs a client for the retask.agent.v1.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &agentServiceClient{
		getAgents: connect.NewClient[v1.AgentsRequest, v1.AgentsResponse](
			httpClient,
			baseURL+AgentServiceGetAgentsProcedure,
			connect.WithSchema(agentServiceGetAgentsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v11.Id, v1.Agent](
			httpClient,
			baseURL+AgentServiceGetAgentProcedure,
			connect.WithSchema(agentServiceGetAgentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setAgent: connect.NewClient[v1.Agent, v11.Id](
			httpClient,
			baseURL+AgentServiceSetAgentProcedure,
			connect.WithSchema(agentServiceSetAgentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteAgent: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+AgentServiceDeleteAgentProcedure,
			connect.WithSchema(agentServiceDeleteAgentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSuggestedAgents: connect.NewClient[v1.SuggestedAgentsRequest, v1.SuggestedAgentsResponse](
			httpClient,
			baseURL+AgentServiceGetSuggestedAgentsProcedure,
			connect.WithSchema(agentServiceGetSuggestedAgentsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	getAgents          *connect.Client[v1.AgentsRequest, v1.AgentsResponse]
	getAgent           *connect.Client[v11.Id, v1.Agent]
	setAgent           *connect.Client[v1.Agent, v11.Id]
	deleteAgent        *connect.Client[v11.Id, v11.Empty]
	getSuggestedAgents *connect.Client[v1.SuggestedAgentsRequest, v1.SuggestedAgentsResponse]
}

// GetAgents calls retask.agent.v1.AgentService.GetAgents.
func (c *agentServiceClient) GetAgents(ctx context.Context, req *connect.Request[v1.AgentsRequest]) (*connect.Response[v1.AgentsResponse], error) {
	return c.getAgents.CallUnary(ctx, req)
}

// GetAgent calls retask.agent.v1.AgentService.GetAgent.
func (c *agentServiceClient) GetAgent(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.Agent], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// SetAgent calls retask.agent.v1.AgentService.SetAgent.
func (c *agentServiceClient) SetAgent(ctx context.Context, req *connect.Request[v1.Agent]) (*connect.Response[v11.Id], error) {
	return c.setAgent.CallUnary(ctx, req)
}

// DeleteAgent calls retask.agent.v1.AgentService.DeleteAgent.
func (c *agentServiceClient) DeleteAgent(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteAgent.CallUnary(ctx, req)
}

// GetSuggestedAgents calls retask.agent.v1.AgentService.GetSuggestedAgents.
func (c *agentServiceClient) GetSuggestedAgents(ctx context.Context, req *connect.Request[v1.SuggestedAgentsRequest]) (*connect.Response[v1.SuggestedAgentsResponse], error) {
	return c.getSuggestedAgents.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the retask.agent.v1.AgentService service.
type AgentServiceHandler interface {
	// === Agent CRUD ===
	GetAgents(context.Context, *connect.Request[v1.AgentsRequest]) (*connect.Response[v1.AgentsResponse], error)
	GetAgent(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Agent], error)
	SetAgent(context.Context, *connect.Request[v1.Agent]) (*connect.Response[v11.Id], error)
	DeleteAgent(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
	// === Suggestions ===
	GetSuggestedAgents(context.Context, *connect.Request[v1.SuggestedAgentsRequest]) (*connect.Response[v1.SuggestedAgentsResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceGetAgentsHandler := connect.NewUnaryHandler(
		AgentServiceGetAgentsProcedure,
		svc.GetAgents,
		connect.WithSchema(agentServiceGetAgentsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetAgentHandler := connect.NewUnaryHandler(
		AgentServiceGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentServiceGetAgentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSetAgentHandler := connect.NewUnaryHandler(
		AgentServiceSetAgentProcedure,
		svc.SetAgent,
		connect.WithSchema(agentServiceSetAgentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteAgentHandler := connect.NewUnaryHandler(
		AgentServiceDeleteAgentProcedure,
		svc.DeleteAgent,
		connect.WithSchema(agentServiceDeleteAgentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetSuggestedAgentsHandler := connect.NewUnaryHandler(
		AgentServiceGetSuggestedAgentsProcedure,
		svc.GetSuggestedAgents,
		connect.WithSchema(agentServiceGetSuggestedAgentsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/retask.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceGetAgentsProcedure:
			agentServiceGetAgentsHandler.ServeHTTP(w, r)
		case AgentServiceGetAgentProcedure:
			agentServiceGetAgentHandler.ServeHTTP(w, r)
		case AgentServiceSetAgentProcedure:
			agentServiceSetAgentHandler.ServeHTTP(w, r)
		case AgentServiceDeleteAgentProcedure:
			agentServiceDeleteAgentHandler.ServeHTTP(w, r)
		case AgentServiceGetSuggestedAgentsProcedure:
			agentServiceGetSuggestedAgentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) GetAgents(context.Context, *connect.Request[v1.AgentsRequest]) (*connect.Response[v1.AgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.agent.v1.AgentService.GetAgents is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAgent(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.agent.v1.AgentService.GetAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetAgent(context.Context, *connect.Request[v1.Agent]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.agent.v1.AgentService.SetAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteAgent(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.agent.v1.AgentService.DeleteAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetSuggestedAgents(context.Context, *connect.Request[v1.SuggestedAgentsRequest]) (*connect.Response[v1.SuggestedAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.agent.v1.AgentService.GetSuggestedAgents is not implemented"))
}
