// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: retask/sandbox/v1/sandbox.proto

package sandboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "nweb.xyz/go/api-contracts-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SandboxService_GetSandboxes_FullMethodName          = "/retask.sandbox.v1.SandboxService/GetSandboxes"
	SandboxService_GetSandbox_FullMethodName            = "/retask.sandbox.v1.SandboxService/GetSandbox"
	SandboxService_SetSandbox_FullMethodName            = "/retask.sandbox.v1.SandboxService/SetSandbox"
	SandboxService_StopSandbox_FullMethodName           = "/retask.sandbox.v1.SandboxService/StopSandbox"
	SandboxService_DeleteSandbox_FullMethodName         = "/retask.sandbox.v1.SandboxService/DeleteSandbox"
	SandboxService_GetSessions_FullMethodName           = "/retask.sandbox.v1.SandboxService/GetSessions"
	SandboxService_GetSession_FullMethodName            = "/retask.sandbox.v1.SandboxService/GetSession"
	SandboxService_NewSession_FullMethodName            = "/retask.sandbox.v1.SandboxService/NewSession"
	SandboxService_SetPartialSession_FullMethodName     = "/retask.sandbox.v1.SandboxService/SetPartialSession"
	SandboxService_ConnectSession_FullMethodName        = "/retask.sandbox.v1.SandboxService/ConnectSession"
	SandboxService_GetSessionRuntime_FullMethodName     = "/retask.sandbox.v1.SandboxService/GetSessionRuntime"
	SandboxService_StopSession_FullMethodName           = "/retask.sandbox.v1.SandboxService/StopSession"
	SandboxService_DeleteSession_FullMethodName         = "/retask.sandbox.v1.SandboxService/DeleteSession"
	SandboxService_ReportSessionStatus_FullMethodName   = "/retask.sandbox.v1.SandboxService/ReportSessionStatus"
	SandboxService_GetSandboxTemplates_FullMethodName   = "/retask.sandbox.v1.SandboxService/GetSandboxTemplates"
	SandboxService_GetSandboxTemplate_FullMethodName    = "/retask.sandbox.v1.SandboxService/GetSandboxTemplate"
	SandboxService_SetSandboxTemplate_FullMethodName    = "/retask.sandbox.v1.SandboxService/SetSandboxTemplate"
	SandboxService_DeleteSandboxTemplate_FullMethodName = "/retask.sandbox.v1.SandboxService/DeleteSandboxTemplate"
	SandboxService_GetSandboxActivities_FullMethodName  = "/retask.sandbox.v1.SandboxService/GetSandboxActivities"
	SandboxService_GetSandboxUsage_FullMethodName       = "/retask.sandbox.v1.SandboxService/GetSandboxUsage"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxServiceClient interface {
	// === Sandbox CRUD ===
	GetSandboxes(ctx context.Context, in *SandboxesRequest, opts ...grpc.CallOption) (*SandboxesResponse, error)
	GetSandbox(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Sandbox, error)
	SetSandbox(ctx context.Context, in *Sandbox, opts ...grpc.CallOption) (*v1.Id, error)
	StopSandbox(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	DeleteSandbox(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	// === Session ===
	GetSessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsResponse, error)
	GetSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Session, error)
	NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*v1.Id, error)
	SetPartialSession(ctx context.Context, in *v1.PartialData, opts ...grpc.CallOption) (*v1.Id, error)
	ConnectSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*SessionConnectionResponse, error)
	// BE-BE only (service-token auth). Returns the materialized runtime
	// view for a session: the Session, its parent Sandbox, and
	// Sandbox.Config with secret plaintext re-injected into
	// EnvVar.SecretValue.value. The caller (sandbox proxy) is trusted
	// to have already validated end-user authorization via the one-time
	// connect token issued by ConnectSession.
	GetSessionRuntime(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*SessionRuntime, error)
	StopSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	DeleteSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	// BE-BE only (service-token auth). Called by proxy on any session status
	// transition. Triggers async LLM extraction on IDLE and VM shutdown
	// evaluation on TIMEOUT.
	ReportSessionStatus(ctx context.Context, in *ReportSessionStatusRequest, opts ...grpc.CallOption) (*v1.Empty, error)
	// === SandboxTemplate CRUD ===
	GetSandboxTemplates(ctx context.Context, in *SandboxTemplatesRequest, opts ...grpc.CallOption) (*SandboxTemplatesResponse, error)
	GetSandboxTemplate(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*SandboxTemplate, error)
	SetSandboxTemplate(ctx context.Context, in *SandboxTemplate, opts ...grpc.CallOption) (*v1.Id, error)
	DeleteSandboxTemplate(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error)
	// === Activity (read-only) ===
	GetSandboxActivities(ctx context.Context, in *SandboxActivitiesRequest, opts ...grpc.CallOption) (*SandboxActivitiesResponse, error)
	GetSandboxUsage(ctx context.Context, in *SandboxUsageRequest, opts ...grpc.CallOption) (*SandboxUsage, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) GetSandboxes(ctx context.Context, in *SandboxesRequest, opts ...grpc.CallOption) (*SandboxesResponse, error) {
	out := new(SandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetSandboxes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSandbox(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Sandbox, error) {
	out := new(Sandbox)
	err := c.cc.Invoke(ctx, SandboxService_GetSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SetSandbox(ctx context.Context, in *Sandbox, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, SandboxService_SetSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StopSandbox(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, SandboxService_StopSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteSandbox(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, SandboxService_DeleteSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsResponse, error) {
	out := new(SessionsResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetSessions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, SandboxService_GetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, SandboxService_NewSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SetPartialSession(ctx context.Context, in *v1.PartialData, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, SandboxService_SetPartialSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ConnectSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*SessionConnectionResponse, error) {
	out := new(SessionConnectionResponse)
	err := c.cc.Invoke(ctx, SandboxService_ConnectSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSessionRuntime(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*SessionRuntime, error) {
	out := new(SessionRuntime)
	err := c.cc.Invoke(ctx, SandboxService_GetSessionRuntime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StopSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, SandboxService_StopSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteSession(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, SandboxService_DeleteSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ReportSessionStatus(ctx context.Context, in *ReportSessionStatusRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, SandboxService_ReportSessionStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSandboxTemplates(ctx context.Context, in *SandboxTemplatesRequest, opts ...grpc.CallOption) (*SandboxTemplatesResponse, error) {
	out := new(SandboxTemplatesResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetSandboxTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSandboxTemplate(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*SandboxTemplate, error) {
	out := new(SandboxTemplate)
	err := c.cc.Invoke(ctx, SandboxService_GetSandboxTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SetSandboxTemplate(ctx context.Context, in *SandboxTemplate, opts ...grpc.CallOption) (*v1.Id, error) {
	out := new(v1.Id)
	err := c.cc.Invoke(ctx, SandboxService_SetSandboxTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) DeleteSandboxTemplate(ctx context.Context, in *v1.Id, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, SandboxService_DeleteSandboxTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSandboxActivities(ctx context.Context, in *SandboxActivitiesRequest, opts ...grpc.CallOption) (*SandboxActivitiesResponse, error) {
	out := new(SandboxActivitiesResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetSandboxActivities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetSandboxUsage(ctx context.Context, in *SandboxUsageRequest, opts ...grpc.CallOption) (*SandboxUsage, error) {
	out := new(SandboxUsage)
	err := c.cc.Invoke(ctx, SandboxService_GetSandboxUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility
type SandboxServiceServer interface {
	// === Sandbox CRUD ===
	GetSandboxes(context.Context, *SandboxesRequest) (*SandboxesResponse, error)
	GetSandbox(context.Context, *v1.Id) (*Sandbox, error)
	SetSandbox(context.Context, *Sandbox) (*v1.Id, error)
	StopSandbox(context.Context, *v1.Id) (*v1.Empty, error)
	DeleteSandbox(context.Context, *v1.Id) (*v1.Empty, error)
	// === Session ===
	GetSessions(context.Context, *SessionsRequest) (*SessionsResponse, error)
	GetSession(context.Context, *v1.Id) (*Session, error)
	NewSession(context.Context, *NewSessionRequest) (*v1.Id, error)
	SetPartialSession(context.Context, *v1.PartialData) (*v1.Id, error)
	ConnectSession(context.Context, *v1.Id) (*SessionConnectionResponse, error)
	// BE-BE only (service-token auth). Returns the materialized runtime
	// view for a session: the Session, its parent Sandbox, and
	// Sandbox.Config with secret plaintext re-injected into
	// EnvVar.SecretValue.value. The caller (sandbox proxy) is trusted
	// to have already validated end-user authorization via the one-time
	// connect token issued by ConnectSession.
	GetSessionRuntime(context.Context, *v1.Id) (*SessionRuntime, error)
	StopSession(context.Context, *v1.Id) (*v1.Empty, error)
	DeleteSession(context.Context, *v1.Id) (*v1.Empty, error)
	// BE-BE only (service-token auth). Called by proxy on any session status
	// transition. Triggers async LLM extraction on IDLE and VM shutdown
	// evaluation on TIMEOUT.
	ReportSessionStatus(context.Context, *ReportSessionStatusRequest) (*v1.Empty, error)
	// === SandboxTemplate CRUD ===
	GetSandboxTemplates(context.Context, *SandboxTemplatesRequest) (*SandboxTemplatesResponse, error)
	GetSandboxTemplate(context.Context, *v1.Id) (*SandboxTemplate, error)
	SetSandboxTemplate(context.Context, *SandboxTemplate) (*v1.Id, error)
	DeleteSandboxTemplate(context.Context, *v1.Id) (*v1.Empty, error)
	// === Activity (read-only) ===
	GetSandboxActivities(context.Context, *SandboxActivitiesRequest) (*SandboxActivitiesResponse, error)
	GetSandboxUsage(context.Context, *SandboxUsageRequest) (*SandboxUsage, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSandboxServiceServer struct {
}

func (UnimplementedSandboxServiceServer) GetSandboxes(context.Context, *SandboxesRequest) (*SandboxesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxes not implemented")
}
func (UnimplementedSandboxServiceServer) GetSandbox(context.Context, *v1.Id) (*Sandbox, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) SetSandbox(context.Context, *Sandbox) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) StopSandbox(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteSandbox(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) GetSessions(context.Context, *SessionsRequest) (*SessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedSandboxServiceServer) GetSession(context.Context, *v1.Id) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSandboxServiceServer) NewSession(context.Context, *NewSessionRequest) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewSession not implemented")
}
func (UnimplementedSandboxServiceServer) SetPartialSession(context.Context, *v1.PartialData) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPartialSession not implemented")
}
func (UnimplementedSandboxServiceServer) ConnectSession(context.Context, *v1.Id) (*SessionConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectSession not implemented")
}
func (UnimplementedSandboxServiceServer) GetSessionRuntime(context.Context, *v1.Id) (*SessionRuntime, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionRuntime not implemented")
}
func (UnimplementedSandboxServiceServer) StopSession(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteSession(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSandboxServiceServer) ReportSessionStatus(context.Context, *ReportSessionStatusRequest) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSessionStatus not implemented")
}
func (UnimplementedSandboxServiceServer) GetSandboxTemplates(context.Context, *SandboxTemplatesRequest) (*SandboxTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxTemplates not implemented")
}
func (UnimplementedSandboxServiceServer) GetSandboxTemplate(context.Context, *v1.Id) (*SandboxTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxTemplate not implemented")
}
func (UnimplementedSandboxServiceServer) SetSandboxTemplate(context.Context, *SandboxTemplate) (*v1.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSandboxTemplate not implemented")
}
func (UnimplementedSandboxServiceServer) DeleteSandboxTemplate(context.Context, *v1.Id) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSandboxTemplate not implemented")
}
func (UnimplementedSandboxServiceServer) GetSandboxActivities(context.Context, *SandboxActivitiesRequest) (*SandboxActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxActivities not implemented")
}
func (UnimplementedSandboxServiceServer) GetSandboxUsage(context.Context, *SandboxUsageRequest) (*SandboxUsage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxUsage not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_GetSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandboxes(ctx, req.(*SandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandbox(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sandbox)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SetSandbox(ctx, req.(*Sandbox))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StopSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).StopSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_StopSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).StopSandbox(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteSandbox(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSessions(ctx, req.(*SessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSession(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_NewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).NewSession(ctx, req.(*NewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SetPartialSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PartialData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SetPartialSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SetPartialSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SetPartialSession(ctx, req.(*v1.PartialData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ConnectSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ConnectSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ConnectSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ConnectSession(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSessionRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSessionRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSessionRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSessionRuntime(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).StopSession(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteSession(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ReportSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ReportSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ReportSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ReportSessionStatus(ctx, req.(*ReportSessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSandboxTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandboxTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandboxTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandboxTemplates(ctx, req.(*SandboxTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSandboxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandboxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandboxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandboxTemplate(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SetSandboxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SetSandboxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SetSandboxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SetSandboxTemplate(ctx, req.(*SandboxTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_DeleteSandboxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).DeleteSandboxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_DeleteSandboxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).DeleteSandboxTemplate(ctx, req.(*v1.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSandboxActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandboxActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandboxActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandboxActivities(ctx, req.(*SandboxActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetSandboxUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetSandboxUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetSandboxUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetSandboxUsage(ctx, req.(*SandboxUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "retask.sandbox.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSandboxes",
			Handler:    _SandboxService_GetSandboxes_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _SandboxService_GetSandbox_Handler,
		},
		{
			MethodName: "SetSandbox",
			Handler:    _SandboxService_SetSandbox_Handler,
		},
		{
			MethodName: "StopSandbox",
			Handler:    _SandboxService_StopSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _SandboxService_DeleteSandbox_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _SandboxService_GetSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SandboxService_GetSession_Handler,
		},
		{
			MethodName: "NewSession",
			Handler:    _SandboxService_NewSession_Handler,
		},
		{
			MethodName: "SetPartialSession",
			Handler:    _SandboxService_SetPartialSession_Handler,
		},
		{
			MethodName: "ConnectSession",
			Handler:    _SandboxService_ConnectSession_Handler,
		},
		{
			MethodName: "GetSessionRuntime",
			Handler:    _SandboxService_GetSessionRuntime_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _SandboxService_StopSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SandboxService_DeleteSession_Handler,
		},
		{
			MethodName: "ReportSessionStatus",
			Handler:    _SandboxService_ReportSessionStatus_Handler,
		},
		{
			MethodName: "GetSandboxTemplates",
			Handler:    _SandboxService_GetSandboxTemplates_Handler,
		},
		{
			MethodName: "GetSandboxTemplate",
			Handler:    _SandboxService_GetSandboxTemplate_Handler,
		},
		{
			MethodName: "SetSandboxTemplate",
			Handler:    _SandboxService_SetSandboxTemplate_Handler,
		},
		{
			MethodName: "DeleteSandboxTemplate",
			Handler:    _SandboxService_DeleteSandboxTemplate_Handler,
		},
		{
			MethodName: "GetSandboxActivities",
			Handler:    _SandboxService_GetSandboxActivities_Handler,
		},
		{
			MethodName: "GetSandboxUsage",
			Handler:    _SandboxService_GetSandboxUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retask/sandbox/v1/sandbox.proto",
}
