// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: retask/project/v1/project.proto

package projectv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/nwebxyz/retask-cli/proto-gen/common/v1"
	v1 "github.com/nwebxyz/retask-cli/proto-gen/retask/project/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RetaskProjectServiceName is the fully-qualified name of the RetaskProjectService service.
	RetaskProjectServiceName = "retask.project.v1.RetaskProjectService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RetaskProjectServiceGetProjectConfigProcedure is the fully-qualified name of the
	// RetaskProjectService's GetProjectConfig RPC.
	RetaskProjectServiceGetProjectConfigProcedure = "/retask.project.v1.RetaskProjectService/GetProjectConfig"
	// RetaskProjectServiceSetProjectConfigProcedure is the fully-qualified name of the
	// RetaskProjectService's SetProjectConfig RPC.
	RetaskProjectServiceSetProjectConfigProcedure = "/retask.project.v1.RetaskProjectService/SetProjectConfig"
	// RetaskProjectServiceGetExternalProjectsProcedure is the fully-qualified name of the
	// RetaskProjectService's GetExternalProjects RPC.
	RetaskProjectServiceGetExternalProjectsProcedure = "/retask.project.v1.RetaskProjectService/GetExternalProjects"
	// RetaskProjectServiceSetExternalProjectProcedure is the fully-qualified name of the
	// RetaskProjectService's SetExternalProject RPC.
	RetaskProjectServiceSetExternalProjectProcedure = "/retask.project.v1.RetaskProjectService/SetExternalProject"
	// RetaskProjectServiceDeleteExternalProjectProcedure is the fully-qualified name of the
	// RetaskProjectService's DeleteExternalProject RPC.
	RetaskProjectServiceDeleteExternalProjectProcedure = "/retask.project.v1.RetaskProjectService/DeleteExternalProject"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	retaskProjectServiceServiceDescriptor                     = v1.File_retask_project_v1_project_proto.Services().ByName("RetaskProjectService")
	retaskProjectServiceGetProjectConfigMethodDescriptor      = retaskProjectServiceServiceDescriptor.Methods().ByName("GetProjectConfig")
	retaskProjectServiceSetProjectConfigMethodDescriptor      = retaskProjectServiceServiceDescriptor.Methods().ByName("SetProjectConfig")
	retaskProjectServiceGetExternalProjectsMethodDescriptor   = retaskProjectServiceServiceDescriptor.Methods().ByName("GetExternalProjects")
	retaskProjectServiceSetExternalProjectMethodDescriptor    = retaskProjectServiceServiceDescriptor.Methods().ByName("SetExternalProject")
	retaskProjectServiceDeleteExternalProjectMethodDescriptor = retaskProjectServiceServiceDescriptor.Methods().ByName("DeleteExternalProject")
)

// RetaskProjectServiceClient is a client for the retask.project.v1.RetaskProjectService service.
type RetaskProjectServiceClient interface {
	GetProjectConfig(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.ProjectConfig], error)
	SetProjectConfig(context.Context, *connect.Request[v1.ProjectConfig]) (*connect.Response[v11.Id], error)
	GetExternalProjects(context.Context, *connect.Request[v1.ExternalProjectsRequest]) (*connect.Response[v1.ExternalProjectsResponse], error)
	SetExternalProject(context.Context, *connect.Request[v1.ExternalProject]) (*connect.Response[v11.Id], error)
	DeleteExternalProject(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
}

// NewRetaskProjectServiceClient constructs a client for the retask.project.v1.RetaskProjectService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRetaskProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RetaskProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &retaskProjectServiceClient{
		getProjectConfig: connect.NewClient[v11.Id, v1.ProjectConfig](
			httpClient,
			baseURL+RetaskProjectServiceGetProjectConfigProcedure,
			connect.WithSchema(retaskProjectServiceGetProjectConfigMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setProjectConfig: connect.NewClient[v1.ProjectConfig, v11.Id](
			httpClient,
			baseURL+RetaskProjectServiceSetProjectConfigProcedure,
			connect.WithSchema(retaskProjectServiceSetProjectConfigMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getExternalProjects: connect.NewClient[v1.ExternalProjectsRequest, v1.ExternalProjectsResponse](
			httpClient,
			baseURL+RetaskProjectServiceGetExternalProjectsProcedure,
			connect.WithSchema(retaskProjectServiceGetExternalProjectsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setExternalProject: connect.NewClient[v1.ExternalProject, v11.Id](
			httpClient,
			baseURL+RetaskProjectServiceSetExternalProjectProcedure,
			connect.WithSchema(retaskProjectServiceSetExternalProjectMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteExternalProject: connect.NewClient[v11.Id, v11.Empty](
			httpClient,
			baseURL+RetaskProjectServiceDeleteExternalProjectProcedure,
			connect.WithSchema(retaskProjectServiceDeleteExternalProjectMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// retaskProjectServiceClient implements RetaskProjectServiceClient.
type retaskProjectServiceClient struct {
	getProjectConfig      *connect.Client[v11.Id, v1.ProjectConfig]
	setProjectConfig      *connect.Client[v1.ProjectConfig, v11.Id]
	getExternalProjects   *connect.Client[v1.ExternalProjectsRequest, v1.ExternalProjectsResponse]
	setExternalProject    *connect.Client[v1.ExternalProject, v11.Id]
	deleteExternalProject *connect.Client[v11.Id, v11.Empty]
}

// GetProjectConfig calls retask.project.v1.RetaskProjectService.GetProjectConfig.
func (c *retaskProjectServiceClient) GetProjectConfig(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v1.ProjectConfig], error) {
	return c.getProjectConfig.CallUnary(ctx, req)
}

// SetProjectConfig calls retask.project.v1.RetaskProjectService.SetProjectConfig.
func (c *retaskProjectServiceClient) SetProjectConfig(ctx context.Context, req *connect.Request[v1.ProjectConfig]) (*connect.Response[v11.Id], error) {
	return c.setProjectConfig.CallUnary(ctx, req)
}

// GetExternalProjects calls retask.project.v1.RetaskProjectService.GetExternalProjects.
func (c *retaskProjectServiceClient) GetExternalProjects(ctx context.Context, req *connect.Request[v1.ExternalProjectsRequest]) (*connect.Response[v1.ExternalProjectsResponse], error) {
	return c.getExternalProjects.CallUnary(ctx, req)
}

// SetExternalProject calls retask.project.v1.RetaskProjectService.SetExternalProject.
func (c *retaskProjectServiceClient) SetExternalProject(ctx context.Context, req *connect.Request[v1.ExternalProject]) (*connect.Response[v11.Id], error) {
	return c.setExternalProject.CallUnary(ctx, req)
}

// DeleteExternalProject calls retask.project.v1.RetaskProjectService.DeleteExternalProject.
func (c *retaskProjectServiceClient) DeleteExternalProject(ctx context.Context, req *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return c.deleteExternalProject.CallUnary(ctx, req)
}

// RetaskProjectServiceHandler is an implementation of the retask.project.v1.RetaskProjectService
// service.
type RetaskProjectServiceHandler interface {
	GetProjectConfig(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.ProjectConfig], error)
	SetProjectConfig(context.Context, *connect.Request[v1.ProjectConfig]) (*connect.Response[v11.Id], error)
	GetExternalProjects(context.Context, *connect.Request[v1.ExternalProjectsRequest]) (*connect.Response[v1.ExternalProjectsResponse], error)
	SetExternalProject(context.Context, *connect.Request[v1.ExternalProject]) (*connect.Response[v11.Id], error)
	DeleteExternalProject(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error)
}

// NewRetaskProjectServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRetaskProjectServiceHandler(svc RetaskProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	retaskProjectServiceGetProjectConfigHandler := connect.NewUnaryHandler(
		RetaskProjectServiceGetProjectConfigProcedure,
		svc.GetProjectConfig,
		connect.WithSchema(retaskProjectServiceGetProjectConfigMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	retaskProjectServiceSetProjectConfigHandler := connect.NewUnaryHandler(
		RetaskProjectServiceSetProjectConfigProcedure,
		svc.SetProjectConfig,
		connect.WithSchema(retaskProjectServiceSetProjectConfigMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	retaskProjectServiceGetExternalProjectsHandler := connect.NewUnaryHandler(
		RetaskProjectServiceGetExternalProjectsProcedure,
		svc.GetExternalProjects,
		connect.WithSchema(retaskProjectServiceGetExternalProjectsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	retaskProjectServiceSetExternalProjectHandler := connect.NewUnaryHandler(
		RetaskProjectServiceSetExternalProjectProcedure,
		svc.SetExternalProject,
		connect.WithSchema(retaskProjectServiceSetExternalProjectMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	retaskProjectServiceDeleteExternalProjectHandler := connect.NewUnaryHandler(
		RetaskProjectServiceDeleteExternalProjectProcedure,
		svc.DeleteExternalProject,
		connect.WithSchema(retaskProjectServiceDeleteExternalProjectMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/retask.project.v1.RetaskProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RetaskProjectServiceGetProjectConfigProcedure:
			retaskProjectServiceGetProjectConfigHandler.ServeHTTP(w, r)
		case RetaskProjectServiceSetProjectConfigProcedure:
			retaskProjectServiceSetProjectConfigHandler.ServeHTTP(w, r)
		case RetaskProjectServiceGetExternalProjectsProcedure:
			retaskProjectServiceGetExternalProjectsHandler.ServeHTTP(w, r)
		case RetaskProjectServiceSetExternalProjectProcedure:
			retaskProjectServiceSetExternalProjectHandler.ServeHTTP(w, r)
		case RetaskProjectServiceDeleteExternalProjectProcedure:
			retaskProjectServiceDeleteExternalProjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRetaskProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRetaskProjectServiceHandler struct{}

func (UnimplementedRetaskProjectServiceHandler) GetProjectConfig(context.Context, *connect.Request[v11.Id]) (*connect.Response[v1.ProjectConfig], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.project.v1.RetaskProjectService.GetProjectConfig is not implemented"))
}

func (UnimplementedRetaskProjectServiceHandler) SetProjectConfig(context.Context, *connect.Request[v1.ProjectConfig]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.project.v1.RetaskProjectService.SetProjectConfig is not implemented"))
}

func (UnimplementedRetaskProjectServiceHandler) GetExternalProjects(context.Context, *connect.Request[v1.ExternalProjectsRequest]) (*connect.Response[v1.ExternalProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.project.v1.RetaskProjectService.GetExternalProjects is not implemented"))
}

func (UnimplementedRetaskProjectServiceHandler) SetExternalProject(context.Context, *connect.Request[v1.ExternalProject]) (*connect.Response[v11.Id], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.project.v1.RetaskProjectService.SetExternalProject is not implemented"))
}

func (UnimplementedRetaskProjectServiceHandler) DeleteExternalProject(context.Context, *connect.Request[v11.Id]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("retask.project.v1.RetaskProjectService.DeleteExternalProject is not implemented"))
}
