// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: public/v1/public.proto

package publicv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "nweb.xyz/go/api-contracts-gen/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PublicService_GetWorkspaceInvitation_FullMethodName     = "/public.v1.PublicService/GetWorkspaceInvitation"
	PublicService_DeclineWorkspaceInvitation_FullMethodName = "/public.v1.PublicService/DeclineWorkspaceInvitation"
)

// PublicServiceClient is the client API for PublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicServiceClient interface {
	GetWorkspaceInvitation(ctx context.Context, in *WorkspaceInvitationRequest, opts ...grpc.CallOption) (*WorkspaceInvitation, error)
	DeclineWorkspaceInvitation(ctx context.Context, in *WorkspaceInvitationRequest, opts ...grpc.CallOption) (*v1.Empty, error)
}

type publicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicServiceClient(cc grpc.ClientConnInterface) PublicServiceClient {
	return &publicServiceClient{cc}
}

func (c *publicServiceClient) GetWorkspaceInvitation(ctx context.Context, in *WorkspaceInvitationRequest, opts ...grpc.CallOption) (*WorkspaceInvitation, error) {
	out := new(WorkspaceInvitation)
	err := c.cc.Invoke(ctx, PublicService_GetWorkspaceInvitation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) DeclineWorkspaceInvitation(ctx context.Context, in *WorkspaceInvitationRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, PublicService_DeclineWorkspaceInvitation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicServiceServer is the server API for PublicService service.
// All implementations must embed UnimplementedPublicServiceServer
// for forward compatibility
type PublicServiceServer interface {
	GetWorkspaceInvitation(context.Context, *WorkspaceInvitationRequest) (*WorkspaceInvitation, error)
	DeclineWorkspaceInvitation(context.Context, *WorkspaceInvitationRequest) (*v1.Empty, error)
	mustEmbedUnimplementedPublicServiceServer()
}

// UnimplementedPublicServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPublicServiceServer struct {
}

func (UnimplementedPublicServiceServer) GetWorkspaceInvitation(context.Context, *WorkspaceInvitationRequest) (*WorkspaceInvitation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspaceInvitation not implemented")
}
func (UnimplementedPublicServiceServer) DeclineWorkspaceInvitation(context.Context, *WorkspaceInvitationRequest) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclineWorkspaceInvitation not implemented")
}
func (UnimplementedPublicServiceServer) mustEmbedUnimplementedPublicServiceServer() {}

// UnsafePublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicServiceServer will
// result in compilation errors.
type UnsafePublicServiceServer interface {
	mustEmbedUnimplementedPublicServiceServer()
}

func RegisterPublicServiceServer(s grpc.ServiceRegistrar, srv PublicServiceServer) {
	s.RegisterService(&PublicService_ServiceDesc, srv)
}

func _PublicService_GetWorkspaceInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).GetWorkspaceInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_GetWorkspaceInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).GetWorkspaceInvitation(ctx, req.(*WorkspaceInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_DeclineWorkspaceInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).DeclineWorkspaceInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_DeclineWorkspaceInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).DeclineWorkspaceInvitation(ctx, req.(*WorkspaceInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicService_ServiceDesc is the grpc.ServiceDesc for PublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "public.v1.PublicService",
	HandlerType: (*PublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkspaceInvitation",
			Handler:    _PublicService_GetWorkspaceInvitation_Handler,
		},
		{
			MethodName: "DeclineWorkspaceInvitation",
			Handler:    _PublicService_DeclineWorkspaceInvitation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/v1/public.proto",
}
