// Copyright 2026 NWEB.xyz

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: auth/v1/user_access.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Per-caller access flags for an entity, computed server-side on read for
// the authenticated user. Never persisted.
//
// Services that carry a role (workspace, project) wrap this message with
// their own role enum (e.g. WorkspaceUserAccess, ProjectUserAccess) so the
// role is returned alongside the action flags. Sharing-based entities
// (sandbox, session, template) and role-less entities (task) use this
// message directly.
//
// can_view is intentionally omitted: if the server returned the entity,
// the caller can view it.
type UserAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanEdit   bool `protobuf:"varint,1,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	CanDelete bool `protobuf:"varint,2,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
}

func (x *UserAccess) Reset() {
	*x = UserAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_user_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccess) ProtoMessage() {}

func (x *UserAccess) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccess.ProtoReflect.Descriptor instead.
func (*UserAccess) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_access_proto_rawDescGZIP(), []int{0}
}

func (x *UserAccess) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *UserAccess) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

var File_auth_v1_user_access_proto protoreflect.FileDescriptor

var file_auth_v1_user_access_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x22, 0x46, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x61, 0x6e, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x89, 0x01, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x2c, 0x6e, 0x77, 0x65, 0x62, 0x2e, 0x78, 0x79, 0x7a, 0x2f, 0x72, 0x65, 0x74, 0x61, 0x73, 0x6b,
	0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x75, 0x74, 0x68, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x41, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x41, 0x75, 0x74, 0x68, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x07,
	0x41, 0x75, 0x74, 0x68, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x13, 0x41, 0x75, 0x74, 0x68, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08,
	0x41, 0x75, 0x74, 0x68, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_v1_user_access_proto_rawDescOnce sync.Once
	file_auth_v1_user_access_proto_rawDescData = file_auth_v1_user_access_proto_rawDesc
)

func file_auth_v1_user_access_proto_rawDescGZIP() []byte {
	file_auth_v1_user_access_proto_rawDescOnce.Do(func() {
		file_auth_v1_user_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_v1_user_access_proto_rawDescData)
	})
	return file_auth_v1_user_access_proto_rawDescData
}

var file_auth_v1_user_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_v1_user_access_proto_goTypes = []interface{}{
	(*UserAccess)(nil), // 0: auth.v1.UserAccess
}
var file_auth_v1_user_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_user_access_proto_init() }
func file_auth_v1_user_access_proto_init() {
	if File_auth_v1_user_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_v1_user_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_v1_user_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_user_access_proto_goTypes,
		DependencyIndexes: file_auth_v1_user_access_proto_depIdxs,
		MessageInfos:      file_auth_v1_user_access_proto_msgTypes,
	}.Build()
	File_auth_v1_user_access_proto = out.File
	file_auth_v1_user_access_proto_rawDesc = nil
	file_auth_v1_user_access_proto_goTypes = nil
	file_auth_v1_user_access_proto_depIdxs = nil
}
